/* ============================================================================
   questions.js — Banco de preguntas.
   Formato:
     { id, m: módulo, d: 'n' (normal) | 'h' (difícil/desafío),
       t: 'mcq' | 'vf' | 'multi',
       q: enunciado, o: [opciones], c: índice correcto (o array si multi),
       e: explicación, s: fuente }
   Regla de calidad: toda pregunta se apoya en una fuente identificable.
   ========================================================================== */

window.QUESTIONS = [

/* ══════════════ M1 — Covarianza, correlación y matrices ══════════════ */
{id:'q001',m:'m1',d:'n',t:'mcq',
 q:'¿Cuál es la principal ventaja de la correlación sobre la covarianza?',
 o:['Detecta relaciones no lineales que la covarianza no capta',
    'Es adimensional y está acotada entre −1 y 1, lo que permite comparar variables medidas en escalas distintas',
    'Siempre es positiva, lo que facilita su interpretación',
    'Permite establecer causalidad entre las variables'],
 c:1,
 e:'La correlación es la versión estandarizada de la covarianza: al dividir por las desviaciones estándar se eliminan las unidades. Queda entre −1 y 1, y una relación lineal perfecta da ±1. Las otras opciones son falsas: ambas miden solo relación LINEAL, r puede ser negativa, y ninguna prueba causalidad.',
 s:'PPT «1. Correlación», diap. 15–16 y 20.'},

{id:'q002',m:'m1',d:'n',t:'vf',
 q:'Var(X) es un caso particular de covarianza, concretamente Cov(X, X).',
 o:['Verdadero','Falso'], c:0,
 e:'Correcto. Cov(X,X) = E[(X−μ)(X−μ)] = E[(X−μ)²] = Var(X). Por eso la diagonal de la matriz de covarianza Σ contiene las varianzas.',
 s:'PPT «1. Correlación», diap. 14 y 22.'},

{id:'q003',m:'m1',d:'n',t:'mcq',
 q:'Dada la matriz Σ = [[16, 6, 8], [6, 9, 1], [8, 1, 25]], ¿cuál es la correlación entre X₁ y X₂?',
 o:['0.375','0.500','0.667','0.400'], c:1,
 e:'r₁₂ = Cov(X₁,X₂)/√(Var(X₁)·Var(X₂)) = 6/√(16·9) = 6/√144 = 6/12 = 0.5. Las otras correlaciones de esta matriz son r₁₃ = 8/√(16·25) = 8/20 = 0.4 y r₂₃ = 1/√(9·25) = 1/15 ≈ 0.0667.',
 s:'«Ayudantía 1 2026-20 Enunciado», P1(b) y su pauta en R.'},

{id:'q004',m:'m1',d:'n',t:'mcq',
 q:'Con Σ = [[16,6,8],[6,9,1],[8,1,25]] (X₁ tiempo, X₂ costo, X₃ distancia), ¿qué par de variables tiene la relación lineal más fuerte?',
 o:['X₁ y X₂ (r = 0.5)','X₁ y X₃ (r = 0.4)','X₂ y X₃ (r = 0.067)','X₁ y X₃, porque su covarianza (8) es la mayor'],
 c:0,
 e:'r₁₂ = 0.5, r₁₃ = 0.4, r₂₃ ≈ 0.067. La relación más fuerte es entre X₁ y X₂. La última opción es la trampa: NO se comparan covarianzas crudas porque dependen de las unidades — hay que pasar a correlaciones.',
 s:'«Ayudantia 1 2026-20 Pauta.R», comentario del ítem 1c.'},

{id:'q005',m:'m1',d:'n',t:'mcq',
 q:'¿Cuál es el estadístico para contrastar H₀: ρ = 0 y sus grados de libertad?',
 o:['t = r·√((n−2)/(1−r²)), con n−2 gl','t = r·√((n−1)/(1−r²)), con n−1 gl','z = r·√n, distribución normal estándar','χ² = n·r², con 1 gl'],
 c:0,
 e:'El estadístico es t = r·√((n−2)/(1−r²)) y se distribuye como una t de Student con n−2 grados de libertad. En R lo calcula directamente cor.test(x, y).',
 s:'«Ayudantía 1 2026-20 Enunciado», P2 (hint); «Pauta Pregunta 3 - Prueba 1», inciso c.'},

{id:'q006',m:'m1',d:'h',t:'mcq',
 q:'Una correlación de r ≈ 0.067 entre dos variables NO resulta significativa con n = 100, pero SÍ con n = 1000. ¿Qué conclusión es correcta?',
 o:['El cálculo con n = 100 debe estar mal, porque r no depende de n',
    'La significancia estadística depende del tamaño de muestra: con n grande, correlaciones muy pequeñas pueden volverse significativas sin ser relevantes en la práctica',
    'Con n = 1000 la correlación deja de ser lineal',
    'Significa que la correlación verdadera cambia al aumentar la muestra'],
 c:1,
 e:'El estadístico t = r√((n−2)/(1−r²)) crece con √n. Con el mismo r, aumentar n aumenta t y reduce el p-valor. Por eso significancia estadística ≠ relevancia práctica: con n muy grande casi cualquier correlación resulta significativa.',
 s:'«Ayudantia 1 2026-20 Pauta.R», comentario del ítem 2.'},

{id:'q007',m:'m1',d:'n',t:'vf',
 q:'Cualquier matriz cuadrada podría ser una matriz de correlación.',
 o:['Verdadero','Falso'], c:1,
 e:'FALSO. Debe cumplir las tres condiciones: (1) todos los valores de la diagonal iguales a 1; (2) todos los elementos entre −1 y 1; (3) ser semidefinida positiva (valores propios ≥ 0).',
 s:'«Pauta Pregunta 1 - Prueba 1», afirmación 1.'},

{id:'q008',m:'m1',d:'n',t:'mcq',
 q:'¿Qué garantiza que una matriz simétrica sea válida como matriz de covarianza?',
 o:['Que su determinante sea distinto de cero','Que todos sus elementos sean positivos','Que sea semidefinida positiva, es decir, que todos sus valores propios sean ≥ 0','Que su traza sea igual al número de variables'],
 c:2,
 e:'Σ debe ser simétrica y semidefinida positiva: todos los valores propios ≥ 0, equivalentemente z′Σz ≥ 0 para todo z. El PPT lo señala explícitamente: «Ojo: los valores propios son no negativos (Σ es semidefinida positiva)».',
 s:'PPT «1. Correlación», diap. 23; «Ejercicios preparación - Prueba 1», P10–P13.'},

{id:'q009',m:'m1',d:'h',t:'mcq',
 q:'Para Σ = [[4,1],[1,3]], la forma cuadrática Q = z′Σz es 4z₁² + 2z₁z₂ + 3z₂². ¿Qué se concluye?',
 o:['Σ es definida positiva, porque Q se puede escribir como suma de cuadrados con coeficientes positivos (y además det Σ = 11 > 0 con σ₁² = 4 > 0)',
    'Σ es semidefinida positiva pero no definida positiva, porque el término cruzado es positivo',
    'No se puede concluir nada sin conocer los datos originales',
    'Σ es indefinida porque contiene un término cruzado 2z₁z₂'],
 c:0,
 e:'Completando cuadrados: Q = 4(z₁ + z₂/4)² + (3 − 1/4)z₂² = 4(z₁+0.25z₂)² + 2.75z₂² > 0 para todo z ≠ 0. Vía rápida equivalente para el caso 2×2: σ₁² = 4 > 0 y det(Σ) = 4·3 − 1² = 11 > 0.',
 s:'«Ayudantía 1 2026-20 Enunciado», P4.'},

{id:'q010',m:'m1',d:'n',t:'mcq',
 q:'¿Cuáles son las hipótesis del test de esfericidad de Bartlett?',
 o:['H₀: la matriz de correlación es la identidad vs H₁: es distinta de la identidad',
    'H₀: las varianzas de todas las variables son iguales vs H₁: son distintas',
    'H₀: la matriz es definida positiva vs H₁: no lo es',
    'H₀: ρ = 0 para un par específico de variables vs H₁: ρ ≠ 0'],
 c:0,
 e:'H₀: R = I_p, es decir, todas las correlaciones fuera de la diagonal son cero (ausencia de correlación global). H₁: R ≠ I. Es el chequeo previo para ACP y análisis factorial.',
 s:'PPT «1. Correlación», diap. 27–28.'},

{id:'q011',m:'m1',d:'n',t:'mcq',
 q:'En el test de Bartlett, un p-valor pequeño (p < α) significa que…',
 o:['no hay correlaciones aprovechables y no conviene aplicar ACP',
    'se rechaza H₀: la matriz NO es la identidad, sí hay correlaciones útiles y tiene sentido aplicar ACP o AF',
    'la matriz de correlación no es definida positiva',
    'las variables siguen una distribución normal multivariada'],
 c:1,
 e:'p pequeño → se rechaza H₀ (R = I) → la matriz difiere de la identidad → existe estructura de correlación aprovechable → los métodos multivariados de reducción tienen sentido. En Bartlett QUEREMOS rechazar H₀.',
 s:'PPT «1. Correlación», diap. 29–30.'},

{id:'q012',m:'m1',d:'h',t:'mcq',
 q:'En la fórmula χ² = −(n − 1 − (2p+5)/6)·ln|R| del test de Bartlett, ¿cuántos grados de libertad tiene el estadístico si hay p = 3 variables?',
 o:['2','3','6','9'], c:1,
 e:'gl = p(p−1)/2 = 3·2/2 = 3. En R: df <- p*(p-1)/2; qchisq(0.95, df). Con p = 4 serían 6 gl, con p = 6 serían 15.',
 s:'«Ayudantía 1 2026-20 Enunciado», P3 y «Ayudantia 1 2026-20 Pauta.R».'},

{id:'q013',m:'m1',d:'h',t:'mcq',
 q:'Si la matriz de correlación R es exactamente la identidad, ¿cuánto vale el estadístico de Bartlett?',
 o:['Infinito','Cero, porque |I| = 1 y ln(1) = 0','Igual a n − 1','No está definido'],
 c:1,
 e:'El determinante de la identidad es 1 y ln(1) = 0, así que χ² = 0. Cuanto más correlacionadas están las variables, más cerca de 0 queda |R|, más negativo es ln|R| y mayor resulta el estadístico.',
 s:'Derivación de la fórmula del PPT «1. Correlación», diap. 27–30.'},

{id:'q014',m:'m1',d:'n',t:'mcq',
 q:'Con Cov(mat, física) = 0.047, Var(mat) = 1.162 y Var(física) = 0.302, ¿cuál es la correlación?',
 o:['0.0793','0.1556','0.0405','0.4700'], c:0,
 e:'r = 0.047/√(1.162 × 0.302) = 0.047/√0.3509 = 0.047/0.5924 = 0.0793. Correlación prácticamente nula.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso c.'},

{id:'q015',m:'m1',d:'n',t:'mcq',
 q:'¿Qué devuelve cor.test(x, y, method = "pearson") en R?',
 o:['Solo el coeficiente de correlación','El coeficiente, un intervalo de confianza y el p-valor para H₀: ρ = 0','La matriz de covarianza completa','La recta de regresión ajustada'],
 c:1,
 e:'cor.test() entrega el coeficiente de correlación, su intervalo de confianza y el p-valor del contraste H₀: ρ = 0. Si solo quieres el coeficiente, se usa cor(x, y).',
 s:'PPT «1. Correlación», diap. 19.'},

{id:'q016',m:'m1',d:'n',t:'multi',
 q:'Selecciona TODAS las propiedades correctas del coeficiente de correlación r.',
 o:['Es adimensional','Siempre está entre −1 y 1','r = 0 implica que las variables son independientes','Una relación lineal perfecta da r = ±1','Una correlación alta demuestra causalidad'],
 c:[0,1,3],
 e:'r es adimensional, está acotado en [−1,1] y vale ±1 con relación lineal perfecta. Las dos falsas: r = 0 NO implica independencia en general (solo bajo normalidad conjunta), y la correlación NO prueba causalidad.',
 s:'PPT «1. Correlación», diap. 16 y 20; «Pauta Pregunta 1 - Prueba 1».'},

/* ══════════════ M2 — Escalamiento y distancias ══════════════ */
{id:'q020',m:'m2',d:'n',t:'vf',
 q:'Con la normalización min-máx la variable normalizada tiene media 0 y varianza 1.',
 o:['Verdadero','Falso'], c:1,
 e:'FALSO. La transformación que da media 0 y desviación 1 es la ESTANDARIZACIÓN (z-score). La min-máx lleva la variable al intervalo [0,1], por lo que la media no puede ser 0 ni la desviación 1.',
 s:'«Pauta Pregunta 1 - Prueba 1», afirmación 5.'},

{id:'q021',m:'m2',d:'n',t:'mcq',
 q:'¿Qué método de escalamiento conviene cuando hay outliers marcados?',
 o:['Estandarización z-score','Normalización min-máx','Escalamiento robusto: (x − mediana)/IQR','Normalización L2'],
 c:2,
 e:'El escalamiento robusto usa mediana e IQR, medidas resistentes a valores extremos. La media y la desviación estándar (z-score), y sobre todo el mínimo y el máximo (min-máx), son muy sensibles a outliers.',
 s:'PPT «1. Correlación», diap. 43.'},

{id:'q022',m:'m2',d:'n',t:'mcq',
 q:'Notas de física: mediana = 5.55, Q₁ = 5.325, Q₃ = 5.850. ¿Cuál es el valor escalado robustamente de una nota de 5.7?',
 o:['0.287','0.150','0.525','0.027'], c:0,
 e:'w = (x − mediana)/IQR = (5.7 − 5.55)/(5.850 − 5.325) = 0.15/0.525 = 0.287.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso b.'},

{id:'q023',m:'m2',d:'h',t:'mcq',
 q:'Una variable normalizada con min-máx tiene valor y = 0.2. Si el mínimo original era 100 y el máximo 200, ¿cuál es el valor original?',
 o:['20','102','120','180'], c:2,
 e:'La transformación inversa es x = y(máx − mín) + mín = 0.2·(200 − 100) + 100 = 0.2·100 + 100 = 120. Esta es exactamente la técnica que pide la pauta para «desnormalizar» centroides de clustering.',
 s:'«PAUTA P1 y P2 PRUEBA 2», Pregunta 1(d).'},

{id:'q024',m:'m2',d:'n',t:'mcq',
 q:'Para los vectores A = (2,3) y B = (6,8), ¿cuáles son las distancias euclídea y Manhattan?',
 o:['6.40 y 9','9 y 6.40','5 y 9','41 y 9'], c:0,
 e:'Euclídea = √((6−2)² + (8−3)²) = √(16+25) = √41 ≈ 6.403 (línea recta). Manhattan = |6−2| + |8−3| = 4 + 5 = 9 (suma de diferencias absolutas). La Manhattan siempre es ≥ la euclídea.',
 s:'PPT «1. Correlación», diap. 47.'},

{id:'q025',m:'m2',d:'n',t:'mcq',
 q:'¿Por qué conviene estandarizar antes de calcular distancias o aplicar ACP/clustering?',
 o:['Para que los datos sigan una distribución normal',
    'Para evitar que una variable con valores grandes domine el análisis solo por su escala',
    'Para eliminar los valores atípicos',
    'Porque las funciones de R lo exigen'],
 c:1,
 e:'Si las variables están en unidades distintas, la de mayor magnitud absoluta domina las distancias y los componentes. Estandarizar las pone en pie de igualdad. No transforma la distribución en normal ni elimina outliers.',
 s:'PPT «1. Correlación», diap. 40 y 46.'},

{id:'q026',m:'m2',d:'h',t:'mcq',
 q:'¿Qué relación exacta hay entre la similitud coseno y la correlación de Pearson?',
 o:['Son siempre idénticas','La correlación es el coseno calculado sobre los vectores previamente CENTRADOS (restando su media)','El coseno es la correlación al cuadrado','No tienen relación: uno mide ángulo y el otro relación lineal'],
 c:1,
 e:'Si se centran ambos vectores restándoles su media y luego se calcula el coseno del ángulo entre ellos, se obtiene exactamente r. Sin centrar, el coseno mide solo similitud angular sobre los datos crudos.',
 s:'PPT «1. Correlación», diap. 48–49 (el script calcula ambos y muestra que coinciden).'},

{id:'q027',m:'m2',d:'n',t:'mcq',
 q:'¿Qué hace la función scale(x) en R?',
 o:['Lleva los datos al rango [0,1]','Estandariza: resta la media y divide por la desviación estándar (media 0, sd 1)','Divide por la norma del vector','Ordena los datos de menor a mayor'],
 c:1,
 e:'scale() hace la estandarización z-score automáticamente. Aplicado a un data.frame estandariza todas las columnas numéricas.',
 s:'PPT «1. Correlación», diap. 42; «Ayudantia 1 2026-20 Pauta.R», ítem 6.'},

{id:'q028',m:'m2',d:'n',t:'mcq',
 q:'¿Cuándo es preferible la normalización L2 (dividir por √(Σxᵢ²))?',
 o:['Cuando hay outliers','Cuando importa la dirección del vector más que su magnitud','Cuando las variables son categóricas','Cuando se quiere media 0'],
 c:1,
 e:'La normalización L2 deja el vector con norma 1, preservando su dirección. Es útil cuando el patrón o la orientación importa más que la escala absoluta.',
 s:'PPT «1. Correlación», diap. 44.'},

{id:'q029',m:'m2',d:'h',t:'multi',
 q:'¿En cuáles de estas situaciones conviene escalar las variables? Selecciona todas.',
 o:['Las variables están medidas en unidades distintas','Se van a usar medidas de distancia','Se va a aplicar ACP o clustering','Todas las variables ya son porcentajes en la misma escala y con rangos comparables'],
 c:[0,1,2],
 e:'El PPT lista exactamente las tres primeras. La cuarta no lo requiere: si todo está ya en la misma escala y rango, escalar no es necesario (y a veces distorsiona diferencias de dispersión que sí son informativas).',
 s:'PPT «1. Correlación», diap. 40.'},

/* ══════════════ M3 — Normal multivariada ══════════════ */
{id:'q030',m:'m3',d:'n',t:'mcq',
 q:'¿Qué dos elementos caracterizan completamente a una distribución normal multivariada?',
 o:['La media y la mediana','Un vector de medias μ y una matriz de covarianza Σ','El número de variables y el tamaño de muestra','Los valores propios y la traza'],
 c:1,
 e:'«Normal multivariada = media + covarianza». μ mueve el centro (dónde está la nube); Σ determina la forma (dispersión) y la inclinación (correlación).',
 s:'PPT «1. Correlación», diap. 32 y 34.'},

{id:'q031',m:'m3',d:'n',t:'mcq',
 q:'En una normal bivariada, ¿qué forma tienen las curvas de igual densidad?',
 o:['Círculos siempre','Rectángulos','Elipses','Rectas paralelas'], c:2,
 e:'En 2D los contornos de densidad constante son elipses (elipsoides en p dimensiones), definidas por la distancia de Mahalanobis (x−μ)′Σ⁻¹(x−μ) = c². Solo son círculos en el caso particular de varianzas iguales y correlación cero.',
 s:'PPT «1. Correlación», diap. 34; PPT «2. Pruebas de Hipótesis», diap. 46.'},

{id:'q032',m:'m3',d:'n',t:'vf',
 q:'Si dos variables son independientes, su correlación es 0.',
 o:['Verdadero','Falso'], c:0,
 e:'VERDADERO. Si son independientes, E(XY) = E(X)E(Y), entonces Cov(X,Y) = E(XY) − E(X)E(Y) = 0, y por tanto r = 0. Esta dirección de la implicación siempre vale.',
 s:'«Pauta Pregunta 1 - Prueba 1», afirmación 2.'},

{id:'q033',m:'m3',d:'n',t:'vf',
 q:'Si dos variables tienen correlación 0, entonces son independientes.',
 o:['Verdadero','Falso'], c:1,
 e:'FALSO en general. Puede haber relación no lineal con r = 0; o la varianza de Y puede depender de X sin que cambie su media. La equivalencia solo se cumple cuando ambas tienen distribución normal conjunta (normal bivariada).',
 s:'«Pauta Pregunta 1 - Prueba 1», afirmación 3; PPT «1. Correlación», diap. 36.'},

{id:'q034',m:'m3',d:'h',t:'mcq',
 q:'Sea X ~ N₂(μ, Σ) con μ = (1, 2)′ y Σ = [[4,1],[1,3]]. Si Y = X₁ + X₂, ¿cuál es la distribución de Y?',
 o:['N(3, 7)','N(3, 9)','N(3, 3)','N(2, 9)'], c:1,
 e:'E(Y) = μ₁ + μ₂ = 1 + 2 = 3. Var(Y) = σ₁² + σ₂² + 2σ₁₂ = 4 + 3 + 2(1) = 9. Por tanto Y ~ N(3, 9), con sd = 3. Quien responde N(3,7) olvidó el término 2σ₁₂.',
 s:'PPT «1. Correlación», diap. 38–39.'},

{id:'q035',m:'m3',d:'h',t:'mcq',
 q:'Con Y ~ N(3, 9), ¿cuál es P(Y ≤ 5)?',
 o:['≈ 0.5000','≈ 0.7475','≈ 0.9772','≈ 0.2525'], c:1,
 e:'Z = (5 − 3)/3 = 0.667. P(Z ≤ 0.667) ≈ 0.7475. En R: pnorm(5, mean = 3, sd = 3).',
 s:'PPT «1. Correlación», diap. 39 (código R del ejemplo).'},

{id:'q036',m:'m3',d:'h',t:'mcq',
 q:'Si Y = X₁ − X₂ con Var(X₁) = 4, Var(X₂) = 3 y Cov(X₁,X₂) = 1, ¿cuánto vale Var(Y)?',
 o:['9','7','5','1'], c:2,
 e:'Var(X₁ − X₂) = σ₁² + σ₂² − 2σ₁₂ = 4 + 3 − 2(1) = 5. Para la SUMA el término cruzado se suma; para la DIFERENCIA se resta. Es un error muy común confundirlo.',
 s:'Propiedad general de Y = a′X ~ N(a′μ, a′Σa); PPT «1. Correlación», diap. 38.'},

{id:'q037',m:'m3',d:'n',t:'mcq',
 q:'En una normal bivariada, si ρ = 0, entonces…',
 o:['X₁ y X₂ son independientes (esto solo se cumple por la normalidad)',
    'X₁ y X₂ pueden seguir siendo dependientes de forma no lineal',
    'la matriz Σ deja de ser definida positiva',
    'las variables tienen la misma varianza'],
 c:0,
 e:'El PPT lo marca como «propiedad importante»: si ρ = 0, entonces X₁ y X₂ son independientes SOLAMENTE en el caso normal. En general (fuera de la normalidad) correlación cero no implica independencia.',
 s:'PPT «1. Correlación», diap. 36.'},

{id:'q038',m:'m3',d:'n',t:'mcq',
 q:'¿Cuáles son los pasos para resolver un ejercicio de combinación lineal de una normal multivariada?',
 o:['Calcular la matriz de correlación, luego los autovalores',
    'Identificar μ y Σ → calcular la media de Y → calcular la varianza de Y → aplicar normal univariada',
    'Estandarizar los datos y aplicar ACP',
    'Calcular la distancia de Mahalanobis y compararla con χ²'],
 c:1,
 e:'Es la secuencia exacta que indica el PPT. La clave es que cualquier combinación lineal a′X de una normal multivariada sigue siendo normal UNIVARIADA, con media a′μ y varianza a′Σa.',
 s:'PPT «1. Correlación», diap. 38.'},

/* ══════════════ M4 — Lógica de las pruebas de hipótesis ══════════════ */
{id:'q040',m:'m4',d:'n',t:'vf',
 q:'Si no rechazo la hipótesis nula, puedo estar seguro de que es verdadera.',
 o:['Verdadero','Falso'], c:1,
 e:'FALSO. Solo sé que la evidencia no es suficiente para rechazarla; puedo estar cometiendo un error tipo II. La prueba NO demuestra que H₀ sea verdadera o falsa: solo evalúa si hay evidencia para rechazarla.',
 s:'«Pauta Pregunta 1 - Prueba 1», afirmación 4; PPT «2. Pruebas de Hipótesis», diap. 2.'},

{id:'q041',m:'m4',d:'n',t:'mcq',
 q:'¿Qué es exactamente el nivel de significancia α?',
 o:['La probabilidad de que H₀ sea verdadera',
    'La probabilidad máxima de cometer un Error Tipo I, es decir, rechazar H₀ cuando en realidad es verdadera',
    'La probabilidad de cometer un error tipo II',
    'El complemento del p-valor'],
 c:1,
 e:'α = P(rechazar H₀ | H₀ verdadera). Es el riesgo máximo de falsa alarma que el investigador acepta. Valores comunes: 0.01, 0.05, 0.10.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 4 y 39.'},

{id:'q042',m:'m4',d:'n',t:'mcq',
 q:'¿Qué es el p-valor?',
 o:['La probabilidad de que la hipótesis nula sea verdadera',
    'La probabilidad de obtener un resultado tan extremo o más extremo que el observado, asumiendo que H₀ es verdadera',
    'La probabilidad de cometer un error tipo II',
    'El nivel de confianza de la prueba'],
 c:1,
 e:'Es la definición exacta del PPT. Ojo con la primera opción: es el malentendido más común sobre el p-valor — NO es la probabilidad de que H₀ sea cierta.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 14.'},

{id:'q043',m:'m4',d:'n',t:'vf',
 q:'Si se decide usar α = 0.01, mientras más grande sea el tamaño de la muestra, menor será la probabilidad de cometer un error tipo I.',
 o:['Verdadero','Falso'], c:1,
 e:'FALSO. La probabilidad de cometer un error tipo I es justamente α, que sigue siendo 0.01 aunque aumente el tamaño de la muestra. Lo que sí disminuye al aumentar n es β (error tipo II), y por tanto aumenta la potencia.',
 s:'«Pauta Pregunta 1 - Prueba 1», afirmación 6.'},

{id:'q044',m:'m4',d:'n',t:'mcq',
 q:'Un experimento arroja p-value = 0.0517 con α = 0.05. ¿Cuál es la decisión correcta?',
 o:['Se rechaza H₀ porque está muy cerca de 0.05','NO se rechaza H₀, porque 0.0517 > 0.05','Se debe repetir el experimento antes de decidir','Se acepta H₀ como verdadera'],
 c:1,
 e:'La regla es estricta: se rechaza solo si p ≤ α. Con 0.0517 > 0.05 no se rechaza H₀, aunque sea un caso límite. En el ejemplo del PPT, el IC del 95% además contiene μ₀ = 10, lo que lo confirma. Y nunca se «acepta» H₀.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 8.'},

{id:'q045',m:'m4',d:'n',t:'mcq',
 q:'¿Qué es la potencia de una prueba?',
 o:['1 − α','1 − β: la capacidad de detectar un efecto real','α + β','El p-valor mínimo alcanzable'],
 c:1,
 e:'Potencia = 1 − β. Es la probabilidad de rechazar H₀ cuando efectivamente es falsa, es decir, de detectar un efecto que sí existe. A mayor potencia, mejor la prueba.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 39.'},

{id:'q046',m:'m4',d:'h',t:'mcq',
 q:'¿Cuál de estas relaciones entre α, β, n y la potencia es INCORRECTA?',
 o:['Si disminuimos α, aumenta β','A mayor n, menor β y mayor potencia','A mayor n, menor α','β depende de la diferencia real entre el valor verdadero y el valor bajo H₀'],
 c:2,
 e:'α NO depende de n: es un valor fijado por el investigador. Las otras tres son correctas: existe un trade-off α↔β, aumentar n reduce β, y β depende de n, α, la diferencia real y la variabilidad σ.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 39 y 41.'},

{id:'q047',m:'m4',d:'n',t:'mcq',
 q:'Un estudio quiere demostrar que la esperanza de vida promedio es MAYOR a 70 años. ¿Cómo se plantean las hipótesis?',
 o:['H₀: μ > 70 vs H₁: μ ≤ 70','H₀: μ ≤ 70 vs H₁: μ > 70','H₀: μ = 70 vs H₁: μ ≠ 70','H₀: μ ≥ 70 vs H₁: μ < 70'],
 c:1,
 e:'Lo que se quiere demostrar va en H₁. H₀ es el status quo y siempre contiene la igualdad: H₀: μ ≤ 70 vs H₁: μ > 70 (unilateral derecha).',
 s:'PPT «2. Pruebas de Hipótesis», diap. 3.'},

{id:'q048',m:'m4',d:'h',t:'mcq',
 q:'Una empresa afirma que «como máximo el 15% de sus parabrisas no cumplen con las especificaciones». Para evaluar esa afirmación, ¿cómo se plantean las hipótesis?',
 o:['H₀: p > 0.15 vs H₁: p ≤ 0.15','H₀: p ≤ 0.15 vs H₁: p > 0.15','H₀: p = 0.15 vs H₁: p ≠ 0.15','H₀: p ≥ 0.15 vs H₁: p < 0.15'],
 c:1,
 e:'La afirmación de la empresa (p ≤ 0.15) es el status quo y va en H₀ — además contiene la igualdad, requisito de H₀. Buscamos evidencia EN CONTRA: H₁: p > 0.15. Es la lógica inversa al caso «quiero demostrar que...», y por eso confunde.',
 s:'«Ayudantía 2 2026-20 Enunciado», P1.'},

{id:'q049',m:'m4',d:'n',t:'mcq',
 q:'Con un nivel de confianza del 90% y prueba bilateral, ¿qué valor se usa para buscar el valor crítico?',
 o:['α = 0.90','α = 0.10, y como es bilateral se busca con α/2 = 0.05','α = 0.05','α = 0.10 sin dividir'],
 c:1,
 e:'Nivel de confianza 90% ⟹ α = 1 − 0.90 = 0.10. En una prueba bilateral el área se reparte en dos colas, así que se busca el crítico con α/2 = 0.05 en cada una.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 4 y 13; «Pauta Pregunta 3 - Prueba 1».'},

{id:'q050',m:'m4',d:'n',t:'multi',
 q:'Según las rúbricas de las pautas del curso, ¿qué elementos debe contener la resolución de una prueba de hipótesis para obtener el puntaje completo? Selecciona todos.',
 o:['Planteamiento de H₀ y H₁','Cálculo del estadístico de prueba','Valor crítico o p-valor y la decisión explícita','Conclusión redactada en el contexto del problema','El gráfico de la distribución con el área sombreada'],
 c:[0,1,2,3],
 e:'Las pautas asignan puntaje por los cuatro primeros pasos (≈0.4 / 0.7-0.8 / 0.5-0.6 / 0.4 pts). El gráfico no es exigido. La conclusión en contexto vale puntos y se obtiene con solo una frase bien redactada.',
 s:'Rúbricas de «Pauta Pregunta 2 y 3 - Prueba 1».'},

/* ══════════════ M5 — Una población ══════════════ */
{id:'q055',m:'m5',d:'n',t:'mcq',
 q:'¿Cuándo se usa la distribución t en lugar de la normal para contrastar una media?',
 o:['Cuando n < 30 siempre','Cuando la varianza poblacional σ² es DESCONOCIDA','Cuando los datos no son normales','Cuando la prueba es bilateral'],
 c:1,
 e:'El criterio es el conocimiento de σ: si σ² es desconocida se usa t de Student (con n−1 gl), que tiene colas más anchas para compensar la incertidumbre de estimar σ con s. Si σ² es conocida se usa z.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 5 y 10.'},

{id:'q056',m:'m5',d:'n',t:'mcq',
 q:'En una prueba t de una muestra con n = 20, ¿cuántos grados de libertad tiene el estadístico?',
 o:['20','19','18','21'], c:1,
 e:'gl = n − 1 = 19. En el ejemplo del consumo eléctrico del PPT, el valor crítico era t(19 gl, α=0.05) = 1.73.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 6.'},

{id:'q057',m:'m5',d:'n',t:'mcq',
 q:'¿Qué requisito hay que verificar SIEMPRE antes de aplicar la prueba Z para proporciones?',
 o:['Que n > 100','Que np₀ ≥ 5 y n(1−p₀) ≥ 5','Que p̂ esté entre 0.2 y 0.8','Que los datos sean normales'],
 c:1,
 e:'Es el «recordatorio importante» del PPT: np₀ ≥ 5 y n(1−p₀) ≥ 5 garantizan la validez de la aproximación normal. Si no se cumple, hay que usar un método exacto como la prueba binomial exacta.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 12 y 43.'},

{id:'q058',m:'m5',d:'n',t:'mcq',
 q:'Con n = 120 y p₀ = 0.40, ¿se cumple el requisito de la aproximación normal?',
 o:['No, porque 120 × 0.40 = 48 es demasiado grande','Sí: 120 × 0.40 = 48 ≥ 5 y 120 × 0.60 = 72 ≥ 5','No se puede saber sin conocer p̂','No, hace falta n ≥ 200'],
 c:1,
 e:'Ambas condiciones se verifican con p₀ (el valor bajo H₀), no con p̂: 48 ≥ 5 ✓ y 72 ≥ 5 ✓.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 12.'},

{id:'q059',m:'m5',d:'h',t:'mcq',
 q:'De 120 estudiantes, 43 trabajan. Se contrasta H₀: p = 0.40. ¿Cuál es el estadístico Z observado (aprox.)?',
 o:['−0.93','−0.42','0.93','−2.10'], c:0,
 e:'p̂ = 43/120 = 0.3583. Z = (0.3583 − 0.40)/√(0.40×0.60/120) = −0.0417/√0.002 = −0.0417/0.04472 ≈ −0.93. Con α = 0.10 bilateral, los críticos son ±1.64, así que no se rechaza H₀.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 12–13.'},

{id:'q060',m:'m5',d:'n',t:'mcq',
 q:'¿Cuál es el estadístico de prueba para la varianza y sus grados de libertad?',
 o:['χ² = n·s²/σ₀², con n gl','χ² = (n−1)·s²/σ₀², con n−1 gl','F = s²/σ₀², con (n−1, n−1) gl','t = (s² − σ₀²)/(s/√n), con n−1 gl'],
 c:1,
 e:'χ² = (n−1)·s²/σ₀², distribuido como chi-cuadrado con n−1 grados de libertad.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 17.'},

{id:'q061',m:'m5',d:'h',t:'mcq',
 q:'Se afirma que la desviación estándar es como máximo 2 minutos. Con n = 24 y s² = 4.9, ¿cuánto vale el estadístico χ²?',
 o:['29.40','28.175','58.80','24.50'], c:1,
 e:'H₀: σ² ≤ 4 (porque σ ≤ 2 ⟹ σ² ≤ 4). χ² = (24−1)·4.9/4 = 23·4.9/4 = 112.7/4 = 28.175. Como χ²(0.05, 23) = 35.172 y 28.175 < 35.172, no se rechaza H₀.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 18.'},

{id:'q062',m:'m5',d:'h',t:'mcq',
 q:'H₀: σ²_B = 25 vs H₁: σ²_B > 25, con n = 12 y s² = 36. ¿Cuál es χ²₀ y cuál la decisión con α = 0.05, si χ²(0.05, 11) = 19.6751?',
 o:['χ²₀ = 15.84 → NO se rechaza H₀','χ²₀ = 15.84 → se rechaza H₀','χ²₀ = 17.28 → se rechaza H₀','χ²₀ = 21.12 → se rechaza H₀'],
 c:0,
 e:'χ²₀ = (12−1)·36/25 = 396/25 = 15.84, con 11 gl. Como 15.84 < 19.6751, no se rechaza H₀: no hay evidencia de que la varianza exceda la especificación de 25.0 ml².',
 s:'«Pauta Pregunta 2 - Prueba 1», inciso a.'},

{id:'q063',m:'m5',d:'n',t:'mcq',
 q:'¿Por qué en R hay que calcular manualmente la prueba χ² para una varianza?',
 o:['Porque el estadístico no está tabulado','Porque R no tiene una función built-in específica para la prueba χ² de varianzas de una muestra (a diferencia de t.test)','Porque la distribución χ² no está implementada en R','Porque solo se puede hacer con el paquete psych'],
 c:1,
 e:'El PPT lo dice explícitamente. Hay que usar qchisq() para los valores críticos y pchisq() para los p-valores. Nota: var.test() sí existe, pero es para comparar DOS varianzas (prueba F), no una contra un valor de referencia.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 19.'},

{id:'q064',m:'m5',d:'h',t:'mcq',
 q:'En una prueba unilateral derecha con z.test(), R devuelve «IC 95%: [10.189, Inf)». ¿Cómo se interpreta?',
 o:['Hay un error en el cálculo, un IC no puede ser infinito',
    'Es correcto: en la prueba unilateral derecha solo interesa el límite inferior, y como μ₀ = 10 queda fuera del intervalo, se rechaza H₀',
    'Significa que la media muestral es infinita',
    'Indica que la varianza es desconocida'],
 c:1,
 e:'En una prueba de cola derecha el intervalo tiene límite superior Inf porque solo importa cuán grande puede ser μ. Como 10 < 10.189, μ₀ queda fuera del IC, lo que confirma el rechazo (p = 0.0153 < 0.05).',
 s:'PPT «2. Pruebas de Hipótesis», diap. 11.'},

{id:'q065',m:'m5',d:'n',t:'mcq',
 q:'¿Qué paquete de R se necesita para la función z.test()?',
 o:['psych','BSDA','ICSNP','stats (viene en R base)'], c:1,
 e:'z.test() está en el paquete BSDA. Los otros paquetes del curso: psych (KMO, cortest.bartlett, fa, describe), ICSNP (HotellingsT2), MVN (test de Mardia), car (ellipse).',
 s:'PPT «2. Pruebas de Hipótesis», diap. 10–11; script «2. Pruebas de Hipótesis. Ejemplos R».'},

{id:'q066',m:'m5',d:'h',t:'mcq',
 q:'En prop.test(78, 120, 0.6, "greater", correct = FALSE), R devuelve X-squared = 1.25. ¿Qué relación tiene con el estadístico z manual (1.118)?',
 o:['No tienen relación, son pruebas distintas','X-squared = z², porque 1.118² = 1.25 (y el p-valor es el mismo)','X-squared = 2z','X-squared = z/2'],
 c:1,
 e:'prop.test usa una formulación chi-cuadrado equivalente: X² = z². Con correct = FALSE (sin corrección de continuidad) coincide exactamente con el cálculo manual, y el p-valor es idéntico: 0.1318.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 16; script del curso.'},

{id:'q067',m:'m5',d:'n',t:'mcq',
 q:'Un enunciado dice: «se afirma que la desviación estándar es máximo 0.1 mm». ¿Con qué valor se plantea H₀ en la prueba χ²?',
 o:['σ₀² = 0.1','σ₀² = 0.01','σ₀² = 0.001','σ₀ = 0.1, sin elevar al cuadrado'],
 c:1,
 e:'El estadístico usa VARIANZAS, así que hay que elevar al cuadrado la desviación: σ ≤ 0.1 ⟹ σ₀² = 0.01. Este es uno de los errores de bulto más frecuentes.',
 s:'«Ejercicios preparación - Prueba 1», P8; PPT «2. Pruebas de Hipótesis», diap. 18.'},

{id:'q068',m:'m5',d:'h',t:'mcq',
 q:'¿Por qué en una prueba χ² BILATERAL los dos valores críticos no son opuestos entre sí?',
 o:['Porque el software los calcula mal','Porque la distribución χ² no es simétrica: hay que buscar por separado qchisq(α/2, gl) y qchisq(1−α/2, gl)','Porque los grados de libertad son distintos en cada cola','Porque la varianza no puede ser negativa, así que no hay cola izquierda'],
 c:1,
 e:'La χ² es asimétrica y está definida solo para valores positivos, por lo que sus cuantiles de las dos colas no son simétricos respecto de ningún punto. En la t y la normal, en cambio, sí basta cambiar el signo.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 17–20; «Ayudantía 2 2026-20 Enunciado», P3.'},

/* ══════════════ M6 — Dos poblaciones ══════════════ */
{id:'q070',m:'m6',d:'n',t:'mcq',
 q:'¿Para qué sirve la prueba F antes de comparar dos medias?',
 o:['Para verificar que los datos son normales',
    'Para saber si las varianzas de las dos poblaciones son iguales o diferentes, lo que determina qué prueba t usar',
    'Para calcular la diferencia de medias',
    'Para determinar el tamaño de muestra necesario'],
 c:1,
 e:'La prueba F compara la variabilidad de dos poblaciones. Es un paso previo: si no se rechaza H₀: σ₁²=σ₂² se usa la t pooled; si se rechaza, la t de Welch.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 21–22.'},

{id:'q071',m:'m6',d:'n',t:'mcq',
 q:'¿Cuáles son los grados de libertad del estadístico F = s₁²/s₂²?',
 o:['(n₁ + n₂ − 2)','(n₁ − 1, n₂ − 1)','(n₁, n₂)','(n₁ + n₂ − 1, 1)'], c:1,
 e:'F se distribuye con (n₁−1, n₂−1) grados de libertad: el primero para el numerador, el segundo para el denominador. Si intercambias numerador y denominador, también se intercambian los gl.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 22.'},

{id:'q072',m:'m6',d:'n',t:'mcq',
 q:'Según el criterio explicitado en el curso (Zimmerman, 2004), ¿qué prueba t conviene usar por defecto?',
 o:['La pooled (var.equal = TRUE), porque es más potente',
    'La de Welch (var.equal = FALSE), a menos que se tenga certeza o fuerte evidencia de que las varianzas son iguales',
    'La pareada, porque siempre es más segura',
    'Depende del tamaño de muestra únicamente'],
 c:1,
 e:'Cita textual del PPT: «Actualmente se recomienda usar el test de varianzas diferentes a no ser que uno tenga certeza (o fuerte evidencia) de que son iguales». Welch es además el valor por defecto de t.test() en R.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 37.'},

{id:'q073',m:'m6',d:'h',t:'mcq',
 q:'Línea A: n=10, s²=16. Línea B: n=12, s²=36. Asumiendo varianzas iguales, ¿cuánto vale Sp²?',
 o:['26','27','28','52'], c:1,
 e:'Sp² = [(n_A−1)s²_A + (n_B−1)s²_B]/(n_A+n_B−2) = [9(16) + 11(36)]/(10+12−2) = [144 + 396]/20 = 540/20 = 27. Luego Sp = √27 = 5.196.',
 s:'«Pauta Pregunta 2 - Prueba 1», inciso b.'},

{id:'q074',m:'m6',d:'h',t:'mcq',
 q:'Con x̄_A = 503, x̄_B = 498, Sp = 5.196, n_A = 10 y n_B = 12, ¿cuál es t₀ y cuál la decisión bilateral con α = 0.05 (t crítico = 2.086)?',
 o:['t₀ = 2.247 → se rechaza H₀','t₀ = 2.247 → NO se rechaza H₀','t₀ = 1.847 → NO se rechaza H₀','t₀ = 0.962 → NO se rechaza H₀'],
 c:0,
 e:'t₀ = (503−498)/[5.196·√(1/10 + 1/12)] = 5/[5.196·√0.1833] = 5/[5.196·0.4282] = 5/2.225 = 2.247. Con gl = 20 y α/2 = 0.025, t_crít = 2.086. Como |2.247| > 2.086 se rechaza H₀: los volúmenes promedio difieren.',
 s:'«Pauta Pregunta 2 - Prueba 1», inciso b.'},

{id:'q075',m:'m6',d:'n',t:'mcq',
 q:'¿Cuántos grados de libertad tiene la prueba t pooled con n₁ = 10 y n₂ = 12?',
 o:['22','21','20','9'], c:2,
 e:'gl = n₁ + n₂ − 2 = 10 + 12 − 2 = 20. En cambio, la t de Welch usa una fórmula distinta que suele dar un número no entero.',
 s:'«Pauta Pregunta 2 - Prueba 1»; PPT «2. Pruebas de Hipótesis», diap. 30.'},

{id:'q076',m:'m6',d:'n',t:'mcq',
 q:'En la salida de R aparece «Welch Two Sample t-test, t = −7.781, df = 18.55». ¿Qué revela el df decimal?',
 o:['Que hubo un error de redondeo',
    'Que se usó la prueba de Welch, cuyos grados de libertad se ajustan y pueden no ser enteros',
    'Que hay datos faltantes',
    'Que las muestras son pareadas'],
 c:1,
 e:'Los gl no enteros son la firma de la prueba de Welch: la fórmula ajusta los grados de libertad para compensar la desigualdad de varianzas. En la pooled los gl son siempre enteros (n₁+n₂−2).',
 s:'PPT «2. Pruebas de Hipótesis», diap. 36 y 55; script del curso.'},

{id:'q077',m:'m6',d:'n',t:'mcq',
 q:'¿Qué son las «muestras dependientes» o datos pareados?',
 o:['Muestras del mismo tamaño','Muestras donde cada observación del grupo 1 está naturalmente vinculada a una del grupo 2, como el mismo paciente antes y después','Muestras tomadas el mismo día','Muestras con la misma varianza'],
 c:1,
 e:'Ejemplo típico: medir el mismo paciente antes y después de un tratamiento. Se trabaja con las diferencias d = Antes − Después y se aplica una prueba t de UNA muestra sobre esas diferencias.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 33.'},

{id:'q078',m:'m6',d:'n',t:'mcq',
 q:'¿Qué hace internamente t.test(antes, despues, paired = TRUE)?',
 o:['Compara las medias de los dos grupos como si fueran independientes',
    'Calcula las diferencias d = antes − despues para cada par y prueba si su media es distinta de cero',
    'Ordena ambos vectores y los compara elemento a elemento',
    'Calcula la correlación entre ambas series'],
 c:1,
 e:'Es exactamente equivalente a t.test(antes − despues, mu = 0). El orden importa: si d̄ > 0 con H₁ bilateral, se concluye que "antes" es mayor que "después".',
 s:'PPT «2. Pruebas de Hipótesis», diap. 38.'},

{id:'q079',m:'m6',d:'h',t:'mcq',
 q:'Se quiere probar que el entrenamiento mejora el tiempo en MÁS DE 2 segundos, con datos pareados. ¿Cuál es la forma correcta en R?',
 o:['t.test(antes, despues, paired = TRUE)',
    't.test(antes - 2, despues, alternative = "greater", paired = TRUE)',
    't.test(antes, despues, alternative = "less", paired = TRUE)',
    't.test(antes, despues, var.equal = TRUE)'],
 c:1,
 e:'H₀: μ_antes − μ_después ≤ 2 vs H₁: > 2. Se desplaza una serie para llevar D₀ = 2 a cero. Equivalente: t.test(antes, despues, mu = 2, alternative = "greater", paired = TRUE), o el cálculo manual t = (d̄ − 2)/(s_d/√n).',
 s:'«Ayudantia 3 2026-20 Pauta R.R», Problema 5.'},

{id:'q080',m:'m6',d:'h',t:'mcq',
 q:'En el ejemplo del colesterol (11 pacientes), t₀ = 9.06 y t(0.05, 10) = 1.8125. ¿Qué se concluye?',
 o:['No se rechaza H₀: el medicamento no tiene efecto',
    'Se rechaza H₀: hay evidencia de que el medicamento reduce significativamente el colesterol, y como d̄ > 0 el colesterol después es menor que antes',
    'El resultado es inconcluyente por el tamaño de muestra',
    'Se rechaza H₀, pero el colesterol aumentó'],
 c:1,
 e:'|9.06| > 1.8125 → cae en zona de rechazo → se rechaza H₀. El signo positivo de d̄ = media(antes − después) indica que los valores «después» son menores: el tratamiento redujo el colesterol.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 57.'},

{id:'q081',m:'m6',d:'h',t:'mcq',
 q:'En el ejemplo del limón, se concluye que «no hay evidencia para afirmar que el precio aumentó en más de $1.500». ¿Cuál es la interpretación CORRECTA?',
 o:['Se demostró que el aumento fue menor o igual a $1.500',
    'NO significa que el aumento no haya sido mayor a $1.500; significa que con estos datos y α = 5% no podemos demostrarlo estadísticamente',
    'El precio no aumentó',
    'Hay que aceptar H₀ como verdadera'],
 c:1,
 e:'Es el matiz exacto que redacta la pauta. No rechazar H₀ nunca es demostrar H₀. Posibles razones del no rechazo: variabilidad alta en los datos o tamaño de muestra insuficiente.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 55.'},

{id:'q082',m:'m6',d:'n',t:'mcq',
 q:'var.test(A, B) arroja F = 8.924 con p-value = 0.001388 e IC 95% [2.876, Inf). ¿Qué se concluye?',
 o:['Las varianzas son iguales; usar t pooled',
    'Se rechaza H₀: las varianzas son diferentes (la de A es ~9 veces la de B); corresponde usar Welch',
    'La media de A es 9 veces la de B',
    'La prueba no es válida porque el IC llega a infinito'],
 c:1,
 e:'p = 0.0014 < 0.05 → se rechaza H₀: σ₁² = σ₂². Además el IC de la razón de varianzas no contiene el 1, lo que confirma el rechazo. Con varianzas desiguales, la prueba de medias correcta es Welch.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 26; script del curso.'},

{id:'q083',m:'m6',d:'h',t:'mcq',
 q:'En var.test(), ¿cuál es el valor de referencia que debe contener el IC para NO rechazar H₀?',
 o:['0','1','El valor de la varianza mayor','α'], c:1,
 e:'Como el parámetro es un COCIENTE de varianzas, H₀ dice «razón = 1». Por eso el criterio del IC es el 1, no el 0. En t.test, en cambio, el parámetro es una DIFERENCIA y el valor de referencia es 0 (o D₀).',
 s:'Salida de var.test() reproducida en PPT «2. Pruebas de Hipótesis», diap. 26.'},

/* ══════════════ M7 — Valores límite y β ══════════════ */
{id:'q085',m:'m7',d:'h',t:'mcq',
 q:'Para H₀: μ ≤ μ₀ vs H₁: μ > μ₀, ¿qué valores de la media muestral NO rechazan H₀?',
 o:['x̄ ≤ μ₀ + t_{α,n−1}·s/√n','x̄ ≥ μ₀ − t_{α,n−1}·s/√n','x̄ ≤ μ₀ − t_{α/2,n−1}·s/√n','x̄ ≥ μ₀ + t_{α,n−1}·s/√n'],
 c:0,
 e:'Se despeja x̄ de la condición de no rechazo t_obs ≤ t_{α,n−1}: (x̄−μ₀)/(s/√n) ≤ t_{α,n−1} ⟹ x̄ ≤ μ₀ + t_{α,n−1}·s/√n. Por encima de ese límite se rechaza.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso e.'},

{id:'q086',m:'m7',d:'h',t:'mcq',
 q:'H₀: μ_fis ≤ 5.8, n = 10, Var(fis) = 0.302, nivel de confianza 90% (t_{0.1;9} = 1.383029). ¿Cuál es el valor límite de x̄?',
 o:['5.98','6.04','6.16','5.56'], c:1,
 e:'s = √0.302 = 0.5495. x̄ ≤ 1.383029·(0.5495/√10) + 5.8 = 1.383029·0.17376 + 5.8 = 0.2403 + 5.8 = 6.04. Los valores x̄ ≤ 6.04 no rechazan H₀.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso e.'},

{id:'q087',m:'m7',d:'h',t:'mcq',
 q:'¿Cuáles son los dos pasos para calcular β (probabilidad de error tipo II)?',
 o:['Calcular el p-valor y restarlo de 1',
    '(1) Hallar el valor límite de x̄ usando μ₀; (2) calcular la probabilidad de caer en la zona de NO rechazo bajo la distribución centrada en μ_real',
    'Calcular α y multiplicarlo por n',
    'Calcular el intervalo de confianza y ver si contiene μ_real'],
 c:1,
 e:'El paso crítico es RECENTRAR: el límite se obtiene con μ₀, pero la probabilidad se calcula bajo μ_real. Si vuelves a usar μ₀ en el segundo paso obtendrás 1 − α, que es la respuesta equivocada.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 41–42; «Ayudantía 2 2026-20 Enunciado», P2(c).'},

{id:'q088',m:'m7',d:'h',t:'mcq',
 q:'Ya se determinó que x̄ ≤ 6.04 no rechaza H₀, con s = 0.5495 y n = 10. Si la verdadera media poblacional es d, ¿cómo se expresa la probabilidad de no rechazar?',
 o:['P(T₉ ≤ (6.04 − d)/(0.5495/√10))','P(T₉ ≤ (6.04 − 5.8)/(0.5495/√10))','P(Z ≤ 6.04 − d)','1 − P(T₁₀ ≤ (d − 6.04)/0.5495)'],
 c:0,
 e:'Se estandariza el límite 6.04 usando la media VERDADERA d: P(X̄ ≤ 6.04 | μ = d) = P(T₉ ≤ (6.04 − d)/(s/√n)). La pauta acepta dejar la respuesta expresada así.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso f.'},

{id:'q089',m:'m7',d:'h',t:'mcq',
 q:'En la prueba χ² unilateral derecha, ¿qué valores de la varianza muestral rechazan H₀: σ² ≤ σ₀²?',
 o:['s² > σ₀²·χ²_{1−α,n−1}/(n−1)','s² > σ₀²·(n−1)/χ²_{1−α,n−1}','s² > χ²_{1−α,n−1}·(n−1)','s² > σ₀² + χ²_{1−α,n−1}'],
 c:0,
 e:'De χ²₀ = (n−1)s²/σ₀² > χ²_{1−α,n−1} se despeja s² > σ₀²·χ²_{1−α,n−1}/(n−1). En R: sigma2_0 * qchisq(1-alpha, n-1)/(n-1).',
 s:'«Ayudantía 2 2026-20 Enunciado», P3(b); PPT «2. Pruebas de Hipótesis», diap. 17.'},

{id:'q090',m:'m7',d:'h',t:'mcq',
 q:'Al calcular la potencia de una prueba de proporciones cuando la p verdadera es 0.30, ¿qué error estándar se usa en el segundo paso?',
 o:['√(p₀(1−p₀)/n), con p₀ el valor bajo H₀','√(p_real(1−p_real)/n), es decir, con p = 0.30','√(p̂(1−p̂)/n)','El mismo de siempre, no cambia'],
 c:1,
 e:'El primer paso (límites de p̂) usa p₀ porque describe la distribución bajo H₀. El segundo paso calcula probabilidades bajo la realidad, así que el error estándar debe usar p_real = 0.30.',
 s:'«Ejercicios preparación - Prueba 1», P6 y P7.'},

{id:'q091',m:'m7',d:'n',t:'mcq',
 q:'En R, ¿qué función da el VALOR CRÍTICO de una distribución t?',
 o:['pt(t, gl)','qt(1−α, gl)','dt(t, gl)','rt(n, gl)'], c:1,
 e:'Mnemotecnia: q = quantile → valor crítico; p = probability → probabilidad acumulada (área a la izquierda, para p-valores); d = densidad; r = random (simulación).',
 s:'«Ayudantia 1 2026-20 Pauta.R», ítem 14; script «2. Pruebas de Hipótesis. Ejemplos R».'},

{id:'q092',m:'m7',d:'h',t:'mcq',
 q:'Bolsas con σ = 0.02 conocida, n = 20, H₀: μ = 1 bilateral con α = 0.05. Los límites de no rechazo de x̄ son aproximadamente…',
 o:['[0.99123, 1.00877]','[0.98000, 1.02000]','[0.99560, 1.00440]','[0.96000, 1.04000]'], c:0,
 e:'se = 0.02/√20 = 0.004472. z_{0.025} = 1.96. Límites: 1 ± 1.96·0.004472 = 1 ± 0.008765 ⟹ [0.99123, 1.00877]. Con esos límites se calcula luego β si la media real es 1.005.',
 s:'«Ayudantía 2 2026-20 Enunciado», P2(b) y P2(c).'},

/* ══════════════ M8 — Hotelling ══════════════ */
{id:'q095',m:'m8',d:'n',t:'mcq',
 q:'¿Por qué hacer p pruebas t individuales NO equivale a un contraste conjunto del vector de medias?',
 o:['Porque las pruebas t son menos precisas',
    'Porque el contraste conjunto controla el error global y aprovecha la correlación entre variables; se puede aceptar cada hipótesis por separado y aun así rechazar la conjunta (y viceversa)',
    'Porque las pruebas t requieren normalidad y el T² no',
    'Porque las pruebas t solo sirven para una muestra'],
 c:1,
 e:'Es la idea clave del PPT. Además, según el estadístico usado la región de aceptación puede ser rectangular, lineal, circular o elíptica; el enfoque correcto aprovecha la correlación y conduce a una región ELÍPTICA.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 45.'},

{id:'q096',m:'m8',d:'n',t:'mcq',
 q:'¿Cuál es el estadístico T² de Hotelling para una muestra?',
 o:['T² = (x̄ − μ₀)′ S (x̄ − μ₀)','T² = n·(x̄ − μ₀)′ S⁻¹ (x̄ − μ₀)','T² = n·(x̄ − μ₀)′ (x̄ − μ₀)','T² = (n−1)·S⁻¹·(x̄ − μ₀)'],
 c:1,
 e:'T² = n(x̄ − μ₀)′S⁻¹(x̄ − μ₀), con x̄ el vector de medias y S la matriz de covarianzas muestral insesgada. Contiene la INVERSA de S, que es lo que le permite ponderar por la correlación entre variables.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 47.'},

{id:'q097',m:'m8',d:'n',t:'mcq',
 q:'¿Qué ocurre con el T² de Hotelling cuando p = 1?',
 o:['No está definido','Coincide exactamente con t², el cuadrado del estadístico t de Student','Se convierte en un estadístico F','Es siempre igual a 1'],
 c:1,
 e:'T² es la extensión multivariada de la t de Student, y con una sola variable se reduce exactamente a t². Es la conexión que destaca el PPT.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 47.'},

{id:'q098',m:'m8',d:'h',t:'mcq',
 q:'¿Cuál es la regla de decisión del T² de Hotelling?',
 o:['Rechazar H₀ si T² > [(n−1)p/(n−p)]·F_α(p, n−p)','Rechazar H₀ si T² > F_α(p, n−p)','Rechazar H₀ si T² > χ²_α(p)','Rechazar H₀ si T² < [(n−p)/((n−1)p)]·F_α(p, n−p)'],
 c:0,
 e:'Bajo H₀, [(n−p)/((n−1)p)]·T² ~ F(p, n−p). Despejando: se rechaza si T² supera [(n−1)p/(n−p)]·F_α(p, n−p). El factor de escala es imprescindible.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 47.'},

{id:'q099',m:'m8',d:'n',t:'mcq',
 q:'¿Qué test se usa para verificar la normalidad multivariada antes de aplicar T²?',
 o:['El test de Shapiro-Wilk','El test de asimetría y curtosis de Mardia','El test de Bartlett','El test KMO'],
 c:1,
 e:'El test de Mardia es la opción estándar. En R: MVN::mvn(X, mvnTest = "mardia") o psych::mardia(X). Los contornos de densidad constante son elipsoides definidos por la distancia de Mahalanobis.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 46.'},

{id:'q100',m:'m8',d:'h',t:'mcq',
 q:'¿Cuál es la diferencia entre los IC simultáneos T² (Roy) y los de Bonferroni?',
 o:['Bonferroni es válido para toda combinación lineal; T² solo para las medias originales',
    'T² es válido para toda combinación lineal a′μ y por eso es más ancho; Bonferroni cubre solo las p medias originales y resulta más angosto/preciso',
    'Son idénticos, solo cambia el nombre',
    'Bonferroni no controla el error global'],
 c:1,
 e:'T² (Roy) protege contra cualquier combinación lineal, lo que lo hace más conservador y ancho. Bonferroni reparte α entre las p componentes y produce intervalos más precisos, pero solo válidos para esas p variables.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 50–51.'},

{id:'q101',m:'m8',d:'h',t:'mcq',
 q:'En el ejemplo «cork», el T² rechaza H₀ (p = 0.0023) y solo el IC del contraste (N+S)−(E+W) = [2.18, 15.53] no contiene el 0. ¿Qué se concluye?',
 o:['Los cuatro depósitos son iguales',
    'El depósito NO es igual en las 4 direcciones, y la diferencia está en el eje norte-sur frente al este-oeste, no entre N y S ni entre E y W',
    'Solo la dirección Norte difiere de las demás',
    'El resultado es inconcluyente porque los otros dos IC contienen el 0'],
 c:1,
 e:'Los IC simultáneos identifican QUÉ explica el rechazo. Como N−S = [−3.83, 5.55] y E−W = [−4.98, 6.98] contienen el 0, dentro de cada eje no hay diferencia; la que sí existe es entre los ejes.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 53; script del curso, bloque 8.'},

{id:'q102',m:'m8',d:'n',t:'mcq',
 q:'¿Qué paquete de R contiene la función HotellingsT2()?',
 o:['psych','ICSNP','car','MVN'], c:1,
 e:'ICSNP::HotellingsT2(X, mu = mu0) entrega T², la F y el valor-p. car::ellipse dibuja la región de confianza; MVN::mvn hace el test de Mardia.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 52; script del curso.'},

{id:'q103',m:'m8',d:'h',t:'mcq',
 q:'¿Qué relación hay entre la región de confianza elipsoidal para μ y el test T²?',
 o:['No están relacionadas',
    'μ₀ cae dentro de la región de confianza si y solo si NO se rechaza H₀: μ = μ₀',
    'La región siempre contiene μ₀',
    'La región se calcula con los valores propios de S⁻¹ únicamente'],
 c:1,
 e:'Es la equivalencia test–región de confianza, análoga a la del IC en el caso univariado. La región está centrada en x̄ y sus ejes y orientación los dan los valores y vectores propios de S.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 49.'},

/* ══════════════ M9 — ACP fundamentos ══════════════ */
{id:'q105',m:'m9',d:'n',t:'vf',
 q:'El análisis de componentes principales transforma un conjunto de variables posiblemente correlacionadas en un nuevo conjunto de variables no correlacionadas llamadas componentes principales.',
 o:['Verdadero','Falso'], c:0,
 e:'VERDADERO. Es la definición del método. Los componentes son ortogonales entre sí, lo que implica que no están correlacionados.',
 s:'«Ayudantía 3 2026-20 Enunciado», P1(a).'},

{id:'q106',m:'m9',d:'n',t:'vf',
 q:'El primer componente principal es la combinación lineal que MINIMIZA la varianza de los datos proyectados.',
 o:['Verdadero','Falso'], c:1,
 e:'FALSO. PC1 MAXIMIZA la varianza proyectada: max wᵀSw sujeto a ‖w‖ = 1, lo que lleva a Sw = λw, es decir, al autovector asociado al mayor autovalor λ₁.',
 s:'«Ayudantía 3 2026-20 Enunciado», P1(c); PPT «3. ACP», diap. 11.'},

{id:'q107',m:'m9',d:'n',t:'vf',
 q:'El PCA es un método supervisado porque utiliza información de una variable objetivo para construir los componentes.',
 o:['Verdadero','Falso'], c:1,
 e:'FALSO. El ACP es NO SUPERVISADO: construye los componentes usando únicamente la estructura de covarianza de las variables, sin ninguna variable objetivo o etiqueta.',
 s:'«Ayudantía 3 2026-20 Enunciado», P1(h).'},

{id:'q108',m:'m9',d:'n',t:'vf',
 q:'Reducir la dimensionalidad mediante PCA implica necesariamente perder toda la información contenida en los datos originales.',
 o:['Verdadero','Falso'], c:1,
 e:'FALSO. Solo se pierde la varianza de los componentes DESCARTADOS, que por construcción es la menor. Si se conservan todos los p componentes no se pierde nada: Σλₖ = traza(S).',
 s:'«Ayudantía 3 2026-20 Enunciado», P1(j).'},

{id:'q109',m:'m9',d:'h',t:'vf',
 q:'Si las notas de Matemáticas y Física no presentan correlación entre sí, entonces no tiene sentido aplicar un Análisis de Componentes Principales al conjunto de 6 asignaturas.',
 o:['Verdadero','Falso'], c:1,
 e:'FALSO. El ACP utiliza TODAS las variables del conjunto; que un par concreto no correlacione no invalida la estructura global. Lo que sí condiciona el ACP es la ausencia de correlación en el conjunto (que detecta el test de Bartlett).',
 s:'«Ayudantía 3 2026-20 Enunciado», P1(k).'},

{id:'q110',m:'m9',d:'h',t:'vf',
 q:'Es preferible realizar un ACP usando la matriz de correlaciones, ya que en ese caso todos los valores propios serán mayores que 1.',
 o:['Verdadero','Falso'], c:1,
 e:'FALSO. Con la matriz de correlación los autovalores SUMAN p (número de variables), así que necesariamente algunos son menores que 1 — de hecho, si todos fueran > 1 la regla de Kaiser no descartaría nada y sería inútil. La preferencia por la matriz de correlaciones se justifica por la comparabilidad de escalas, no por esa razón.',
 s:'«Ayudantía 3 2026-20 Enunciado», P1(m).'},

{id:'q111',m:'m9',d:'n',t:'vf',
 q:'La suma de las varianzas explicadas por todos los componentes principales es igual a la suma de las varianzas de las variables originales.',
 o:['Verdadero','Falso'], c:0,
 e:'VERDADERO. Σλₖ = traza(S): la varianza total se conserva bajo la transformación. Por eso se puede hablar de «proporción de varianza explicada» por cada componente.',
 s:'«Ayudantía 3 2026-20 Enunciado», P1(g).'},

{id:'q112',m:'m9',d:'n',t:'mcq',
 q:'¿Cuál es el número máximo de componentes principales que se pueden extraer?',
 o:['Siempre 2, para poder graficar','El número de observaciones n','El número de variables originales p','No hay límite'],
 c:2,
 e:'S es una matriz p×p, así que tiene p autovalores y p autovectores. Al conservar los p componentes se reproduce exactamente la información original.',
 s:'«Ayudantía 3 2026-20 Enunciado», P1(e); PPT «3. ACP».'},

{id:'q113',m:'m9',d:'n',t:'mcq',
 q:'¿Por qué es necesario CENTRAR las variables antes de aplicar ACP?',
 o:['Para que los datos sean normales',
    'Porque si no, el primer componente podría apuntar hacia la media de los datos en lugar de capturar la dirección de máxima variabilidad',
    'Para eliminar outliers',
    'Porque R lo exige'],
 c:1,
 e:'Centrar garantiza que el ACP detecte PATRONES DE VARIACIÓN y no niveles de magnitud. Sin centrar, PC1 tendería a apuntar hacia el centroide de la nube.',
 s:'PPT «3. ACP», diap. 8.'},

{id:'q114',m:'m9',d:'n',t:'mcq',
 q:'En la ecuación S·v = λ·v del ACP, ¿qué representan v y λ?',
 o:['v es la varianza y λ la covarianza',
    'v es un autovector: una dirección de variación. λ es un autovalor: la varianza explicada en esa dirección',
    'v es un loading y λ un score',
    'v es la media y λ la desviación estándar'],
 c:1,
 e:'Cada autovector indica una dirección en el espacio de las variables originales; cada autovalor indica cuánta variabilidad se captura en esa dirección. El ACP ordena las direcciones de mayor a menor λ.',
 s:'PPT «3. ACP», diap. 10.'},

{id:'q115',m:'m9',d:'h',t:'mcq',
 q:'Para S = [[2.333, 0.333],[0.333, 2.333]], los autovalores son λ₁ = 2.666 y λ₂ = 2.000. ¿Qué proporción de la varianza explica PC1?',
 o:['57.1%','50.0%','66.7%','75.0%'], c:0,
 e:'Proporción = λ₁/(λ₁+λ₂) = 2.666/4.666 = 0.5714 ≈ 57.1%. Nota además que λ₁+λ₂ = 4.666 = 2.333+2.333 = traza(S): la varianza total se conserva.',
 s:'PPT «3. ACP», diap. 17 (ejemplo numérico).'},

{id:'q116',m:'m9',d:'h',t:'mcq',
 q:'Con autovectores v₁ = (1/√2)(1,1) y v₂ = (1/√2)(1,−1), ¿cómo se interpretan?',
 o:['v₁ es un contraste y v₂ una suma',
    'v₁: ambas variables pesan igual y en la misma dirección (suman); v₂: contraste entre las dos variables (una resta a la otra)',
    'Ambos son contrastes',
    'v₁ representa la media y v₂ la varianza'],
 c:1,
 e:'Signos iguales ⟹ el componente es un «tamaño» o promedio ponderado. Signos opuestos ⟹ el componente es un «contraste» o diferencia. Es la clave para nombrar componentes.',
 s:'PPT «3. ACP», diap. 17.'},

{id:'q117',m:'m9',d:'n',t:'mcq',
 q:'¿Cuáles son los tres criterios del curso para decidir cuántos componentes conservar?',
 o:['Kaiser (λ > 1), regla del 80% de varianza acumulada y scree plot (codo)',
    'Bartlett, KMO y análisis paralelo',
    'Media, mediana y moda de los autovalores',
    'p-valor, α y potencia'],
 c:0,
 e:'Regla de Kaiser: conservar componentes con autovalor > 1 (solo con datos estandarizados). Regla del 80%: acumular al menos ese porcentaje. Scree plot: buscar el codo donde la curva se aplana.',
 s:'PPT «3. ACP», diap. 15.'},

{id:'q118',m:'m9',d:'h',t:'mcq',
 q:'¿Por qué la regla de Kaiser usa el umbral exactamente 1?',
 o:['Es un número arbitrario elegido por convención',
    'Porque con datos estandarizados cada variable aporta varianza = 1; un componente que explique menos que una variable sola no vale la pena conservarlo',
    'Porque los autovalores nunca superan 1',
    'Porque 1 corresponde al 100% de la varianza'],
 c:1,
 e:'Es la lógica que explicita el PPT. Y de ahí se deriva la restricción: la regla SOLO tiene sentido con datos estandarizados (matriz de correlación), donde cada variable aporta exactamente 1 de varianza.',
 s:'PPT «4.2 Análisis Factorial», diap. 30; PPT «3. ACP», diap. 15.'},

{id:'q119',m:'m9',d:'n',t:'multi',
 q:'Selecciona TODO lo que el ACP NO hace.',
 o:['No distingue por sí mismo variables importantes de no importantes',
    'No garantiza interpretabilidad directa de cada componente',
    'No es adecuado cuando las relaciones entre variables no son lineales',
    'No permite reducir la dimensionalidad'],
 c:[0,1,2],
 e:'Las tres primeras son las limitaciones que lista el PPT. La cuarta es falsa: reducir la dimensionalidad es precisamente lo que sí hace el ACP.',
 s:'PPT «3. ACP», diap. 6.'},

/* ══════════════ M10 — ACP en R ══════════════ */
{id:'q120',m:'m10',d:'n',t:'mcq',
 q:'En summary(pca), la fila «Standard deviation» muestra 1.4617 para PC1. ¿Cuál es el autovalor de PC1?',
 o:['1.4617','2.1366','1.2090','0.5341'], c:1,
 e:'La «Standard deviation» es √λ, así que λ = 1.4617² = 2.1366. Es imprescindible elevarla al cuadrado para aplicar la regla de Kaiser. En R: pca$sdev^2.',
 s:'«Ayudantía 2 2026-20 Enunciado», P5 (salida de R).'},

{id:'q121',m:'m10',d:'h',t:'mcq',
 q:'Con sd(PC1) = 1.4617 y sd(PC2) = 0.9909, ¿cuántos componentes retiene el criterio de Kaiser?',
 o:['Ninguno','1 (solo PC1, porque λ₁ = 2.137 > 1 pero λ₂ = 0.982 < 1)','2','4'],
 c:1,
 e:'λ₁ = 1.4617² = 2.137 > 1 ✓. λ₂ = 0.9909² = 0.982 < 1 ✗ (por muy poco). Kaiser retiene solo PC1. Si se leyera mal la fila como si fueran autovalores, se retendrían 2 y la respuesta sería incorrecta.',
 s:'«Ayudantía 2 2026-20 Enunciado», P5(a).'},

{id:'q122',m:'m10',d:'h',t:'mcq',
 q:'Cumulative Proportion: PC1 = 0.5341, PC2 = 0.7796, PC3 = 0.9655. ¿Cuántos componentes hacen falta según el criterio del 80% de varianza acumulada?',
 o:['1','2','3','4'], c:2,
 e:'PC1+PC2 = 77.96%, que aún NO alcanza el 80%. Hay que llegar a PC3 (96.55%). Este es el caso en que los criterios discrepan: Kaiser y el codo sugieren 1, y el 80% exige 3 — hay que decirlo explícitamente y justificar la elección.',
 s:'«Ayudantía 2 2026-20 Enunciado», P5(a).'},

{id:'q123',m:'m10',d:'n',t:'mcq',
 q:'¿Qué hace scale. = TRUE en prcomp()?',
 o:['Ordena las observaciones','Estandariza las variables (resta la media y divide por la sd), equivalente a trabajar con la matriz de correlación','Escala el gráfico del biplot','Elimina las variables con poca varianza'],
 c:1,
 e:'Es fundamental cuando las variables tienen distintas unidades: sin estandarizar, el ACP trabaja sobre la matriz de covarianza y la variable de mayor varianza absoluta domina los componentes.',
 s:'PPT «3. ACP», diap. 20; script del curso.'},

{id:'q124',m:'m10',d:'n',t:'mcq',
 q:'¿Qué contiene pca$rotation y qué contiene pca$x?',
 o:['$rotation son los scores y $x los loadings',
    '$rotation son los loadings (pesos de cada variable en cada componente); $x son los scores (coordenadas de cada observación)',
    'Ambos contienen los autovalores',
    '$rotation es la matriz de correlación y $x los datos originales'],
 c:1,
 e:'$rotation = loadings, para interpretar QUÉ significa cada componente. $x = scores, las coordenadas de cada observación en el nuevo espacio, para graficar o alimentar otro modelo.',
 s:'PPT «3. ACP», diap. 20 y 25–26.'},

{id:'q125',m:'m10',d:'n',t:'mcq',
 q:'¿Cuál es la regla del curso para interpretar los loadings de un componente?',
 o:['|loading| ≥ 0.10 relevante, ≥ 0.20 fuerte','|loading| ≥ 0.30 relevante, ≥ 0.40 fuerte','|loading| ≥ 0.50 relevante, ≥ 0.80 fuerte','Solo importa el signo'],
 c:1,
 e:'Se interpreta el VALOR ABSOLUTO para decidir si la variable entra, y el SIGNO para leer la dirección: (+) relación positiva, (−) relación negativa con el componente.',
 s:'PPT «3. ACP», diap. 22; «Ayudantia 3 2026-20 Pauta R.R».'},

{id:'q126',m:'m10',d:'h',t:'mcq',
 q:'Un cliente nuevo tiene Gasto = $58.000. ¿Se puede reemplazar directamente ese valor en la expresión de PC1 obtenida con prcomp(scale. = TRUE)?',
 o:['Sí, los loadings se aplican a los valores originales',
    'No: los loadings multiplican variables ESTANDARIZADAS, así que primero hay que estandarizar el caso nuevo usando la media y la sd de la muestra original',
    'No, porque un solo cliente no tiene varianza',
    'Sí, pero dividiendo el resultado por 1000'],
 c:1,
 e:'Meter 58000 crudo haría que esa variable dominara todo el score. Hay que calcular Z = (x − pca$center)/pca$scale y luego aplicar los loadings. En R lo hace automáticamente predict(pca, newdata = nuevo).',
 s:'«Ayudantía 2 2026-20 Enunciado», P5(d).'},

{id:'q127',m:'m10',d:'n',t:'mcq',
 q:'¿Qué función de R aplica correctamente el mismo centrado y escalado a una observación nueva?',
 o:['scale(nuevo)','predict(pca, newdata = nuevo)','prcomp(nuevo)','cor(nuevo)'], c:1,
 e:'predict() reutiliza pca$center y pca$scale, las medias y desviaciones del ajuste original. scale(nuevo) sería incorrecto porque estandarizaría con los estadísticos del propio caso nuevo (indefinidos si es una sola fila).',
 s:'Derivado del procedimiento pedido en «Ayudantía 2 2026-20 Enunciado», P5(d); documentación de prcomp.'},

{id:'q128',m:'m10',d:'h',t:'mcq',
 q:'En mtcars, PC1 tiene loadings positivos altos en cyl, disp, hp y wt, y negativos altos en mpg y drat. ¿Cómo se interpreta?',
 o:['Es un componente sin significado interpretable',
    'Contrasta autos grandes, pesados y potentes frente a autos eficientes y económicos: «tamaño y potencia vs eficiencia»',
    'Mide solo el peso del vehículo',
    'Indica que mpg y drat están mal medidas'],
 c:1,
 e:'Signos opuestos = contraste. PC1 es un eje que va de vehículo grande/pesado/potente a liviano/eficiente. En mtcars, PC1 y PC2 juntos explican ~80% de la varianza.',
 s:'PPT «3. ACP», diap. 23.'},

{id:'q129',m:'m10',d:'n',t:'mcq',
 q:'En un biplot, ¿qué significa que dos flechas (variables) estén muy cercanas entre sí?',
 o:['Que tienen la misma media','Que están correlacionadas positivamente','Que son independientes','Que tienen la misma unidad de medida'],
 c:1,
 e:'Ángulo pequeño ⟹ correlación positiva alta. Flechas opuestas (~180°) ⟹ correlación negativa. Flechas perpendiculares (~90°) ⟹ prácticamente no correlacionadas. Flecha larga ⟹ variable bien representada en ese plano.',
 s:'PPT «3. ACP», diap. 25.'},

{id:'q130',m:'m10',d:'h',t:'mcq',
 q:'En el ACP de las notas (Ayudantía 3), PC1 tiene varianza 3.87 y PC2 tiene 0.84. Según el criterio del codo, ¿dónde está el codo?',
 o:['Entre PC3 y PC4','Entre PC1 y PC2','No hay codo','Entre PC5 y PC6'], c:1,
 e:'La pauta señala que el codo aparece entre PC1 y PC2: es donde cambia bruscamente la pendiente. Además, por Kaiser solo PC1 supera 1. PC1 se interpreta como la «nota general» del alumno.',
 s:'«Ayudantia 3 2026-20 Pauta R.R», bloque 3.'},

{id:'q131',m:'m10',d:'n',t:'mcq',
 q:'¿Qué comando dibuja la línea de referencia de Kaiser sobre un screeplot?',
 o:['abline(h = 1, col = "red", lty = 2)','abline(v = 1)','lines(1)','plot(h = 1)'], c:0,
 e:'abline(h = 1, ...) traza una línea HORIZONTAL en la altura 1, el umbral de Kaiser. Con v = se trazaría vertical. lty = 2 la hace punteada.',
 s:'«Ayudantia 3 2026-20 Pauta R.R», bloque 3.'},

/* ══════════════ M11 — AF: modelo y adecuación ══════════════ */
{id:'q135',m:'m11',d:'n',t:'mcq',
 q:'¿Qué busca el Análisis Factorial?',
 o:['Predecir una variable objetivo a partir de las demás',
    'Factores latentes (no observados) que expliquen las correlaciones entre las variables observadas',
    'Agrupar observaciones en clusters',
    'Eliminar las variables con menor varianza'],
 c:1,
 e:'Es la definición del PPT. Los factores son variables latentes: no se miden directamente, se infieren del patrón de correlaciones entre las variables observadas.',
 s:'PPT «4.2 Análisis Factorial», diap. 45.'},

{id:'q136',m:'m11',d:'n',t:'mcq',
 q:'¿Qué es la comunalidad (h²) de una variable?',
 o:['La correlación entre dos variables',
    'La proporción de la varianza de esa variable explicada por los factores comunes',
    'El número de factores extraídos',
    'La varianza total del modelo'],
 c:1,
 e:'h² es la parte de la varianza debida a los factores comunes. En una solución ortogonal es la suma de los cuadrados de las cargas de esa fila. Su complemento es la unicidad: u² = 1 − h².',
 s:'PPT «4.2 Análisis Factorial», diap. 44; «Ayudantia 3 2026-20 Pauta R.R».'},

{id:'q137',m:'m11',d:'h',t:'mcq',
 q:'En una salida de fa(), Matemáticas tiene h² = 0.26 y u² = 0.737. ¿Cómo se interpreta?',
 o:['Matemáticas es la variable mejor explicada del modelo',
    'Solo el 26% de la varianza de Matemáticas está explicada por los factores: la variable está MAL representada, con mucha información no explicada',
    'Matemáticas tiene una correlación de 0.26 con el factor 1',
    'Hay un error, porque h² + u² debe dar 1'],
 c:1,
 e:'h² bajo = variable mal representada por la estructura factorial. Compara con Química (h² = 1.00, u² = 0.005), prácticamente toda explicada, o Historia (h² = 0.95). Nota: h² + u² ≈ 1 salvo redondeo.',
 s:'«Ayudantia 3 2026-20 Pauta R.R», comentarios del bloque 7.'},

{id:'q138',m:'m11',d:'n',t:'mcq',
 q:'¿Cuáles son los requisitos previos para aplicar Análisis Factorial según el PPT?',
 o:['n > 100 y variables normales',
    'KMO adecuado (> 0.5), test de Bartlett significativo (p < 0.05) y matriz de correlaciones con estructura',
    'Solo que las variables sean numéricas',
    'Que todos los autovalores sean mayores que 1'],
 c:1,
 e:'Son los tres requisitos que lista el resumen del PPT. El KMO evalúa la adecuación muestral; Bartlett, que exista correlación global.',
 s:'PPT «4.2 Análisis Factorial», diap. 45.'},

{id:'q139',m:'m11',d:'n',t:'mcq',
 q:'Según la pauta de la Ayudantía 3, ¿qué valor de Overall MSA (KMO) se espera para que el AF sea aceptable?',
 o:['Mayor a 0.3','Mayor a 0.6','Mayor a 0.9','Menor a 0.5'], c:1,
 e:'«Se espera que Overall MSA sea mayor a 0.6 para que sea aceptable para hacer FA». En el ejemplo de las notas se obtuvo 0.82 («muy adecuado»). El script 4.1 usa una escala algo distinta: ≥0.75 bien, ≥0.50 aceptable, <0.50 inaceptable.',
 s:'«Ayudantia 3 2026-20 Pauta R.R»; PPT «4.2», diap. 41; script «4.1 Análisis Factorial».'},

{id:'q140',m:'m11',d:'h',t:'mcq',
 q:'En USArrests, el KMO global es adecuado pero UrbanPop tiene MSA = 0.49. ¿Qué implica?',
 o:['Hay que descartar todo el análisis',
    'UrbanPop tiene adecuación baja y es candidata a ser eliminada, porque no comparte estructura con las otras variables (que sí son tasas de criminalidad)',
    'UrbanPop es la variable más importante',
    'El KMO global está mal calculado'],
 c:1,
 e:'El KMO se lee a dos niveles: global (Overall MSA) y por variable. Un MSA individual bajo señala una variable que no encaja. Tiene sentido sustantivo: UrbanPop es % de población urbana, no una tasa de arrestos.',
 s:'PPT «4.2 Análisis Factorial», diap. 41.'},

{id:'q141',m:'m11',d:'n',t:'mcq',
 q:'En el test de Bartlett aplicado antes de un AF, ¿qué resultado queremos obtener?',
 o:['p-valor grande, para no rechazar H₀','p-valor pequeño, para rechazar H₀: R = I y confirmar que hay correlaciones aprovechables','Un estadístico cercano a cero','Que el KMO sea menor a 0.5'],
 c:1,
 e:'«p-valor muy pequeño → rechaza H0 → matriz tiene correlaciones (AF es apropiado)». Ojo: el χ² de bondad de ajuste DEL MODELO factorial funciona al revés (ahí queremos NO rechazar).',
 s:'PPT «4.2 Análisis Factorial», diap. 42.'},

{id:'q142',m:'m11',d:'n',t:'mcq',
 q:'¿Cuáles son los tres métodos de extracción que menciona el PPT?',
 o:['Varimax, Promax y Oblimin',
    'Componentes Principales, Ejes Principales y Máxima Verosimilitud',
    'Kaiser, codo y varianza acumulada',
    'KMO, Bartlett y análisis paralelo'],
 c:1,
 e:'Esos son los métodos de EXTRACCIÓN. Varimax/Promax/Oblimin son métodos de ROTACIÓN, y Kaiser/codo/varianza son criterios para el NÚMERO de factores. No hay que confundir las tres categorías.',
 s:'PPT «4.2 Análisis Factorial», diap. 45.'},

{id:'q143',m:'m11',d:'h',t:'mcq',
 q:'En la pauta de la Ayudantía 3 se usa fm = "ml" en fa(). ¿Por qué?',
 o:['Porque es el único método disponible',
    'Es «Maximum Likelihood», método de estimación que asume normalidad y permite obtener un χ² de bondad de ajuste para contrastar si el número de factores es suficiente',
    'Porque produce siempre 2 factores',
    'Porque es más rápido que los demás'],
 c:1,
 e:'Comentario textual de la pauta: «Metodo de estimacion Maximum Likelihood para asumir supuesto de normalidad». Su ventaja práctica es el test χ² del ajuste (en el ejemplo: χ² = 1.21, p = 0.88 → 2 factores bastan).',
 s:'«Ayudantia 3 2026-20 Pauta R.R», bloque 7.'},

/* ══════════════ M12 — AF: rotación e interpretación ══════════════ */
{id:'q145',m:'m12',d:'n',t:'mcq',
 q:'¿Qué NO cambia al rotar los factores?',
 o:['Las cargas factoriales',
    'Las comunalidades, las especificidades y la varianza total explicada',
    'La interpretabilidad de los factores',
    'La distribución de la varianza entre factores'],
 c:1,
 e:'Es la propiedad que destaca el PPT. La rotación solo cambia CÓMO SE DISTRIBUYE la varianza entre los factores y la interpretabilidad. Las cargas individuales sí cambian, pero h², u² y la varianza total explicada permanecen idénticas.',
 s:'PPT «4.2 Análisis Factorial», diap. 36.'},

{id:'q146',m:'m12',d:'n',t:'mcq',
 q:'¿Cuál es el objetivo de la rotación Varimax?',
 o:['Que cada variable se relacione con un solo factor (simplifica filas)',
    'Que cada factor tenga cargas muy altas en algunas variables y muy bajas en las demás (simplifica columnas)',
    'Permitir que los factores estén correlacionados',
    'Reducir el número de factores'],
 c:1,
 e:'Varimax es la rotación ortogonal más utilizada: hace las COLUMNAS (factores) simples de interpretar. La que simplifica FILAS es Quartimax (cada variable en un solo factor), que a veces produce un factor general fuerte poco interpretable.',
 s:'PPT «4.2 Análisis Factorial», diap. 37.'},

{id:'q147',m:'m12',d:'n',t:'mcq',
 q:'¿Cuál es la diferencia entre rotación ortogonal y oblicua?',
 o:['La ortogonal usa más factores',
    'La ortogonal mantiene los factores independientes (no correlacionados); la oblicua permite que estén correlacionados',
    'La oblicua no cambia las cargas',
    'La ortogonal solo funciona con 2 factores'],
 c:1,
 e:'Ortogonales: Varimax, Quartimax, Equamax. Oblicuas: Oblimin, Promax. La oblicua se usa cuando es razonable que los factores compartan varianza — por ejemplo, factores de personalidad.',
 s:'PPT «4.2 Análisis Factorial», diap. 36–38.'},

{id:'q148',m:'m12',d:'h',t:'mcq',
 q:'¿Cómo funciona la rotación Promax?',
 o:['Es idéntica a Varimax','Primero hace una rotación Varimax y luego permite correlación entre factores','Solo funciona con un factor','Elimina los factores con eigenvalue < 1'],
 c:1,
 e:'Promax parte de una solución Varimax y luego relaja la restricción de ortogonalidad. Es rápido y eficiente, y muy común cuando hay muchas variables.',
 s:'PPT «4.2 Análisis Factorial», diap. 38.'},

{id:'q149',m:'m12',d:'n',t:'mcq',
 q:'Según el Principio de Estructura Simple (Thurstone, 1935), una buena solución factorial cumple que…',
 o:['todos los factores tienen cargas similares en todas las variables',
    'cada factor tiene pocas cargas altas y el resto cercanas a cero, y cada variable se asocia principalmente a un solo factor',
    'hay tantos factores como variables',
    'todas las cargas son positivas'],
 c:1,
 e:'Los tres criterios de Thurstone: pocas cargas altas por factor, cada variable asociada principalmente a un factor, y factores con patrones de cargas diferentes. Es lo que la rotación intenta conseguir.',
 s:'PPT «4.2 Análisis Factorial», diap. 36.'},

{id:'q150',m:'m12',d:'n',t:'mcq',
 q:'¿Cuál de los criterios para elegir el número de factores es «el más confiable si las variables están bien seleccionadas y la base teórica es clara»?',
 o:['Regla de Kaiser','Determinación a priori (conocimiento teórico del problema)','Scree plot','% de varianza explicada'],
 c:1,
 e:'El PPT lo señala explícitamente. Los otros tienen problemas conocidos: Kaiser tiende a SUBESTIMAR el número de factores; el % de varianza es arbitrario; el scree plot es subjetivo.',
 s:'PPT «4.2 Análisis Factorial», diap. 30–31.'},

{id:'q151',m:'m12',d:'h',t:'mcq',
 q:'¿Cuál es el problema conocido de la regla de Kaiser en Análisis Factorial?',
 o:['Sobreestima el número de factores','Tiende a SUBESTIMAR el número real de factores','No funciona con datos estandarizados','Requiere más de 100 observaciones'],
 c:1,
 e:'El PPT lo indica textualmente: «Problema: tiende a subestimar el número real de factores». Por eso en la práctica se complementa con el análisis paralelo (fa.parallel).',
 s:'PPT «4.2 Análisis Factorial», diap. 30.'},

{id:'q152',m:'m12',d:'n',t:'mcq',
 q:'En fa.parallel(datos, fa = "fa"), ¿cuál es la regla de decisión?',
 o:['Conservar todos los factores con eigenvalue > 1',
    'Conservar los factores cuyo eigenvalor REAL supere al eigenvalor SIMULADO (línea azul por encima de la roja)',
    'Conservar tantos factores como variables',
    'Conservar los factores con carga > 0.5'],
 c:1,
 e:'El análisis paralelo compara los eigenvalores reales con los de datos aleatorios simulados. Es más robusto que Kaiser porque el umbral se adapta a n y p en vez de ser un 1 fijo.',
 s:'PPT «4.2 Análisis Factorial», diap. 42.'},

{id:'q153',m:'m12',d:'h',t:'mcq',
 q:'En la salida de fa(), la columna «com» (complejidad) vale 2.0 para Química y 1.2 para Inglés. ¿Qué significa?',
 o:['Química tiene comunalidad 2.0',
    'Química depende de AMBOS factores, mientras que Inglés depende principalmente de uno solo (más cercano a la estructura simple ideal)',
    'Química tiene 2 valores faltantes',
    'Inglés explica el 120% de la varianza'],
 c:1,
 e:'«com» indica cuántos factores influyen en una variable. Valor ideal cercano a 1 (estructura simple). Escala: ≈1 simple (ideal), 1–2 moderada (aceptable), >2 compleja (difícil de interpretar).',
 s:'«Ayudantia 3 2026-20 Pauta R.R», comentarios del bloque 7.'},

{id:'q154',m:'m12',d:'h',t:'mcq',
 q:'La salida de fa() muestra «Likelihood Chi Square = 1.21 with prob < 0.88». ¿Qué se concluye?',
 o:['El modelo es malo porque el χ² es muy bajo',
    'No es posible rechazar la hipótesis de que 2 factores son suficientes: el número de factores elegido es adecuado',
    'Hay que rechazar el modelo porque p > 0.05',
    'El test no es aplicable con n = 30'],
 c:1,
 e:'Aquí H₀ dice que el modelo con m factores reproduce bien la matriz de correlaciones, así que un p-valor GRANDE es buena noticia. Es al revés que en el test de Bartlett, donde queremos rechazar.',
 s:'«Ayudantia 3 2026-20 Pauta R.R», bloque 7.'},

{id:'q155',m:'m12',d:'n',t:'mcq',
 q:'En una salida de fa(), «SS loadings: ML1 = 2.57, ML2 = 1.24» y «Proportion Var: 0.43 y 0.21». ¿Qué porcentaje de la varianza total explican los dos factores juntos?',
 o:['21%','43%','64%','100%'], c:2,
 e:'0.43 + 0.21 = 0.64 → 64% de la varianza total. Distinto es «Proportion Explained» (ML1 = 67%, ML2 = 33%), que reparte la varianza COMÚN entre los factores y por eso suma 100%.',
 s:'«Ayudantia 3 2026-20 Pauta R.R», comentarios del bloque 7.'},

{id:'q156',m:'m12',d:'h',t:'mcq',
 q:'En el AF de la encuesta de restaurantes, el Factor 1 tiene cargas altas en «empleados amigables» (0.98), «servicio rápido» (0.82) y «empleados con conocimiento» (0.58). ¿Cómo se nombra?',
 o:['Calidad de la comida','Calidad del servicio','Valor económico percibido','Ambiente del restaurante'],
 c:1,
 e:'Las tres variables se refieren al trato y desempeño del personal. Los otros factores de la pauta: F2 «Calidad de la comida» (sabor 0.96, comida fresca 0.76, temperatura 0.64), F3 «Valor económico percibido» (porciones 0.98, precios 0.94), F4 «Ambiente» (interior atractivo 0.99, lugar entretenido 0.65).',
 s:'«Ayudantia 3 2026-20 Pauta R.R», Pregunta 4.'},

{id:'q157',m:'m12',d:'n',t:'mcq',
 q:'Según el PPT, ¿qué umbral se usa para considerar una carga factorial significativa?',
 o:['Generalmente > |0.5| o > |0.4|','Siempre > |0.9|','Cualquier valor distinto de cero','> |0.1|'], c:0,
 e:'Cita del PPT: «Cargas factoriales significativas: generalmente > |0.5| o > |0.4|». La pauta de ayudantía afina: ≈0.30 débil, ≥0.50 moderada, ≥0.70 fuerte.',
 s:'PPT «4.2 Análisis Factorial», diap. 33; «Ayudantia 3 2026-20 Pauta R.R».'},

{id:'q158',m:'m12',d:'n',t:'mcq',
 q:'En un loading plot, ¿qué indica que una variable esté cerca del origen?',
 o:['Que tiene alta correlación con todos los factores','Que tiene BAJA correlación con todos los factores','Que es la variable más importante','Que su comunalidad es 1'],
 c:1,
 e:'Variables al final de un eje → alta correlación con ese factor. Variables cerca del origen → baja correlación con todos los factores (comunalidad baja, mal representadas).',
 s:'PPT «4.2 Análisis Factorial», diap. 33.'},

{id:'q159',m:'m12',d:'n',t:'multi',
 q:'Selecciona TODAS las rotaciones ORTOGONALES.',
 o:['Varimax','Quartimax','Equamax','Promax','Oblimin'],
 c:[0,1,2],
 e:'Ortogonales (factores independientes): Varimax, Quartimax, Equamax. Oblicuas (factores correlacionados): Oblimin y Promax.',
 s:'PPT «4.2 Análisis Factorial», diap. 37–38.'},

/* ══════════════ M13 — ACP vs AF (lecturas) ══════════════ */
{id:'q165',m:'m13',d:'n',t:'mcq',
 q:'¿Cuál es la diferencia de fondo entre ACP y Análisis Factorial?',
 o:['El ACP explica la VARIANZA de las variables observadas; el AF explica las COVARIANZAS/correlaciones entre ellas',
    'El ACP usa correlaciones y el AF covarianzas',
    'El ACP es supervisado y el AF no',
    'El ACP solo funciona con 2 variables'],
 c:0,
 e:'Es la distinción central de la literatura: el ACP resume lo observado (los componentes son combinaciones lineales exactas); el AF postula factores latentes que CAUSAN las correlaciones observadas.',
 s:'Búsqueda en internet: Universitat de València, «AF vs Componentes Principales»; Minitab. Contrastado con los PPT del curso.'},

{id:'q166',m:'m13',d:'h',t:'mcq',
 q:'¿Cuál de estas afirmaciones distingue correctamente los componentes de los factores?',
 o:['Ambos son variables latentes',
    'En el ACP los componentes son variables observadas (combinaciones lineales exactas de las X); en el AF los factores son variables LATENTES no observadas',
    'En el ACP los componentes son latentes y en el AF observados',
    'Los factores son siempre ortogonales y los componentes no'],
 c:1,
 e:'Un componente principal se calcula exactamente a partir de los datos; un factor se INFIERE del patrón de correlaciones y nunca se observa directamente. De ahí que en el AF exista indeterminación factorial y en el ACP no.',
 s:'Búsqueda en internet: Universitat de València; contrastado con PPT «3» y «4.2».'},

{id:'q167',m:'m13',d:'h',t:'mcq',
 q:'¿En cuál de las dos técnicas existe el concepto de UNICIDAD (varianza específica)?',
 o:['En ambas por igual','Solo en el Análisis Factorial: distingue varianza común (h²) y varianza única (u²)','Solo en el ACP','En ninguna'],
 c:1,
 e:'En el ACP no existe el concepto de unicidad: toda la varianza entra al análisis y no hay término de error por variable. El AF sí descompone la varianza en común (comunalidad) y única (especificidad + error).',
 s:'Búsqueda en internet: Universitat de València; PPT «4.2 Análisis Factorial», diap. 36 y 44.'},

{id:'q168',m:'m13',d:'n',t:'multi',
 q:'Selecciona TODO lo que ACP y Análisis Factorial COMPARTEN.',
 o:['Son técnicas no supervisadas de reducción de dimensiones',
    'Parten de la matriz de correlación o covarianza',
    'Usan criterios similares para decidir cuántas dimensiones conservar (Kaiser, % varianza, scree plot)',
    'Ambos postulan un modelo estadístico con término de error por variable'],
 c:[0,1,2],
 e:'Las tres primeras son comunes. La cuarta es exclusiva del AF: el ACP no asume modelo estadístico, no tiene término de error y no requiere iteraciones ni convergencia.',
 s:'PPT «3» y «4.2» del curso + búsqueda en internet (Universitat de València, Minitab).'},

{id:'q169',m:'m13',d:'h',t:'mcq',
 q:'¿En cuál de estas situaciones es más apropiado usar Análisis Factorial en vez de ACP?',
 o:['Quiero reducir 50 predictores a 5 antes de una regresión',
    'Quiero validar un cuestionario de satisfacción e identificar qué dimensiones teóricas subyacen a las respuestas',
    'Quiero visualizar mis datos en 2D',
    'Quiero eliminar la multicolinealidad de mi modelo'],
 c:1,
 e:'El AF es la herramienta cuando el objetivo es CONOCER LA ESTRUCTURA y plantear una teoría sobre constructos latentes. Las otras tres son usos típicos del ACP, donde interesan las puntuaciones para alimentar otro método.',
 s:'Búsqueda en internet: Universitat de València; ejemplo del restaurante en «Ayudantia 3 2026-20 Pauta R.R».'},

{id:'q170',m:'m13',d:'h',t:'mcq',
 q:'¿Por qué en el ACP la solución es única y en el AF no?',
 o:['Porque el ACP usa menos variables',
    'Porque el ACP es una transformación algebraica determinista, mientras que en el AF distintas rotaciones producen cargas distintas con el mismo ajuste (indeterminación factorial)',
    'Porque el AF requiere más observaciones',
    'Porque el ACP no usa autovalores'],
 c:1,
 e:'La indeterminación factorial es precisamente lo que hace posible (y necesaria) la rotación: se puede girar la solución sin alterar comunalidades ni varianza total explicada, buscando la versión más interpretable.',
 s:'PPT «4.2 Análisis Factorial», diap. 36 + búsqueda en internet (Universitat de València).'},

{id:'q171',m:'m13',d:'n',t:'mcq',
 q:'En el ACP, ¿en qué se suele trabajar después del análisis, y en el AF?',
 o:['En ambos casos con las puntuaciones',
    'En el ACP se trabaja con las puntuaciones (scores) para reducir dimensión; en el AF rara vez se usan las puntuaciones y el objetivo es conocer la estructura',
    'En ambos casos con las cargas',
    'En el ACP con las cargas y en el AF con los autovalores'],
 c:1,
 e:'Diferencia de propósito práctico: el ACP produce nuevas variables útiles para modelar; el AF produce una interpretación teórica de los constructos. (En el ejemplo de las notas, la pauta sí menciona que los puntajes factoriales resultaron fiables y podrían usarse después.)',
 s:'Búsqueda en internet: Universitat de València, «AF vs Componentes Principales».'},

{id:'q172',m:'m13',d:'h',t:'mcq',
 q:'¿Qué contiene la diagonal de la matriz que se analiza en cada técnica (con variables estandarizadas)?',
 o:['ACP: comunalidades · AF: unos',
    'ACP: unos (varianza total de cada variable) · AF: la comunalidad estimada (menor que 1)',
    'En ambos casos ceros',
    'En ambos casos los autovalores'],
 c:1,
 e:'Es la diferencia técnica que explica todo lo demás: el ACP analiza la matriz de correlación completa (diagonal de unos, toda la varianza); el AF sustituye la diagonal por las comunalidades, analizando solo la varianza COMPARTIDA.',
 s:'Búsqueda en internet: Universitat de València, Minitab. Coherente con la descomposición 1 = h² + u² del PPT «4.2».'},

/* ══════════════ M14 — Estrategia y errores ══════════════ */
{id:'q180',m:'m14',d:'n',t:'mcq',
 q:'¿Cuál es la forma correcta de redactar la conclusión de una prueba que no rechaza H₀?',
 o:['«Se acepta H₀: la afirmación es verdadera»',
    '«Con un nivel de significancia del 5%, no existe evidencia estadística suficiente para afirmar que [afirmación en contexto]»',
    '«H₀ es verdadera con un 95% de probabilidad»',
    '«El experimento falló»'],
 c:1,
 e:'Nunca «se acepta H₀». La plantilla de la pauta menciona el nivel de significancia y habla del problema en sus propios términos, no de símbolos. Esa redacción vale ~0.4 pts en la rúbrica.',
 s:'Rúbricas de «Pauta Pregunta 2 y 3 - Prueba 1».'},

{id:'q181',m:'m14',d:'h',t:'mcq',
 q:'Un enunciado afirma: «el promedio de Matemáticas es superior a 4,0 O BIEN el promedio de Física es menor o igual a 5,8». ¿Cómo se aborda?',
 o:['Se hace una sola prueba con ambas medias',
    'Se diseñan DOS hipótesis (una por asignatura); si al menos una de las dos afirmaciones se sostiene, la afirmación global es cierta',
    'Se usa un T² de Hotelling obligatoriamente',
    'La afirmación es imposible de contrastar'],
 c:1,
 e:'Es una disyunción lógica: basta con que UNA de las dos se cumpla. La pauta plantea H₀: μ_mat ≤ 4 vs H₁: μ_mat > 4 (p = 0.07723 < 0.10 → se rechaza, la afirmación de matemáticas es cierta) y H₀: μ_fis ≤ 5.8 vs H₁: > 5.8 (p = 0.7631 > 0.10 → no se rechaza, la afirmación de física es cierta). Como ambas son ciertas, la global también.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso d.'},

{id:'q182',m:'m14',d:'h',t:'mcq',
 q:'Los directivos sostienen que «el promedio de Física supera al de Matemáticas en MÁS de 0,5 puntos». ¿Cuáles son las hipótesis?',
 o:['H₀: μ_fis − μ_mat = 0.5 vs H₁: μ_fis − μ_mat ≠ 0.5',
    'H₀: μ_fis − μ_mat ≤ 0.5 vs H₁: μ_fis − μ_mat > 0.5',
    'H₀: μ_fis − μ_mat ≥ 0.5 vs H₁: μ_fis − μ_mat < 0.5',
    'H₀: μ_fis = μ_mat vs H₁: μ_fis ≠ μ_mat'],
 c:1,
 e:'«Supera en más de 0.5» es lo que se quiere demostrar, así que va en H₁ (unilateral derecha). La pauta señala que es equivalente a H₀: (μ_fis − 0.5) − μ_mat ≤ 0, lo que indica cómo escribir el código de R correcto.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso g.'},

{id:'q183',m:'m14',d:'n',t:'mcq',
 q:'¿Cuál es el enfoque correcto para responder «¿cuál de las dos muestras presenta mayor dispersión?» con dos enfoques distintos?',
 o:['Comparar las medias y las medianas',
    'Comparar las varianzas de la matriz de covarianza, y además el rango intercuartílico (Q3−Q1) o el rango (máx−mín)',
    'Solo mirar el gráfico de cajas',
    'Calcular la correlación entre ambas'],
 c:1,
 e:'La pauta acepta tres formas y exige al menos dos (0.25 pts cada una): (1) varianzas de la matriz de covarianza; (2) rango intercuartílico; (3) rango máx−mín. Todas dieron la misma conclusión en ese ejercicio.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso a y su rúbrica.'},

{id:'q184',m:'m14',d:'h',t:'mcq',
 q:'¿Por qué la pauta admite usar el test de Bartlett para probar la correlación entre solo DOS variables (Matemáticas y Física)?',
 o:['Porque Bartlett siempre funciona',
    'Porque en ese caso la matriz de correlación es 2×2, y probar que R ≠ I equivale a probar que la única correlación fuera de la diagonal es distinta de cero',
    'Porque tiene más potencia que la prueba t',
    'Porque no requiere conocer n'],
 c:1,
 e:'Nota textual de la pauta: «Notar que en este caso es válida la prueba (sirve para mostrar o no correlación entre las notas) pues la matriz de correlación es 2x2». Con p = 2, H₀: R = I es exactamente H₀: ρ = 0.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso c.'},

{id:'q185',m:'m14',d:'n',t:'multi',
 q:'Selecciona TODOS los errores que efectivamente cuestan puntos según las pautas del curso.',
 o:['Escribir «se acepta H₀» en lugar de «no se rechaza H₀»',
    'Usar α en vez de α/2 en una prueba bilateral',
    'Usar σ donde va σ² en la prueba χ²',
    'No escribir la conclusión en el contexto del problema',
    'Presentar los resultados con 4 decimales'],
 c:[0,1,2,3],
 e:'Los cuatro primeros son errores conceptuales o de procedimiento penalizados. Redondear a 4 decimales al presentar es correcto (lo hacen los propios scripts del curso con round(x, 4)); lo importante es calcular con todos los decimales.',
 s:'Rúbricas y desarrollos de las pautas de la Prueba 1.'}

];
