/* ============================================================================
   questions2.js — Banco ampliado.
   Foco: (1) ELEGIR el test correcto, (2) IDENTIFICAR qué número del enunciado
   va en cada lugar, (3) DECIDIR numéricamente, (4) leer salidas de R.
   ========================================================================== */

window.QUESTIONS.push(

/* ═══════════ M15 · ELEGIR EL TEST ═══════════ */
{id:'q200',m:'m15',d:'n',t:'mcq',
 q:'«Se mide el colesterol de 11 pacientes <b>antes y después</b> del tratamiento.» ¿Qué prueba corresponde?',
 o:['t de dos muestras independientes con varianzas iguales (pooled)','t de Welch','t para muestras <b>pareadas</b>','Prueba F de cociente de varianzas'],
 c:2,
 e:'«Los mismos sujetos medidos dos veces» es la señal inequívoca de muestras dependientes. Se trabaja con las diferencias d = Antes − Después y se aplica una t de UNA muestra sobre ellas, con gl = n−1 = 10.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 33 y 57.'},

{id:'q201',m:'m15',d:'n',t:'mcq',
 q:'«Se prueban <b>30 especímenes</b> de la aleación A y <b>30 especímenes</b> de la aleación B.» ¿Son muestras pareadas?',
 o:['Sí, porque tienen el mismo tamaño (n₁ = n₂ = 30)','No: son objetos distintos; que n₁ = n₂ es una coincidencia. Son independientes','Sí, porque se comparan dos grupos','No se puede determinar'],
 c:1,
 e:'Lo que define «pareadas» es que cada observación de un grupo esté VINCULADA a una del otro (mismo sujeto/objeto medido dos veces). 30 especímenes de A y 30 de B son 60 objetos distintos → muestras independientes. Que n₁ = n₂ no significa nada.',
 s:'«Ejercicios preparación - Prueba 1», Problema 1.'},

{id:'q202',m:'m15',d:'h',t:'mcq',
 q:'«Los <b>mismos 10 alumnos</b> rindieron Matemáticas y Física. ¿El promedio de Física supera al de Matemáticas en más de 0,5 puntos?» ¿Qué código de R es el correcto?',
 o:['t.test(fisica, matematicas, var.equal = TRUE, alternative = "greater")',
    't.test(fisica - 0.5, matematicas, paired = TRUE, alternative = "greater")',
    't.test(fisica, matematicas, mu = 0, alternative = "two.sided")',
    'var.test(fisica, matematicas, alternative = "greater")'],
 c:1,
 e:'Dos cosas a la vez: (1) son los MISMOS alumnos → paired = TRUE; (2) D₀ = 0.5, y restar 0.5 a una de las series traslada esa diferencia a cero. La rúbrica de la pauta daba 0.2 puntos solo por elegir este código. Salida real: t = 1.7281, df = 9, p = 0.05902.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso g y Anexo 2.'},

{id:'q203',m:'m15',d:'n',t:'mcq',
 q:'«Se sabe que la desviación estándar del peso de las bolsas <b>debe ser igual a 0,02 kg</b>. Se toma una muestra de 20 bolsas y se quiere saber si la media está centrada en 1 kg.» ¿Qué prueba para la media?',
 o:['Prueba t con 19 gl','Prueba <b>z</b>, porque σ es conocida','Prueba χ²','Prueba F'],
 c:1,
 e:'El enunciado entrega σ = 0.02 como un valor conocido de la máquina (no estimado de la muestra), así que corresponde la prueba z. El criterio NO es el tamaño de muestra: es si σ es conocida o no.',
 s:'«Ayudantía 2 2026-20 Enunciado», P2; PPT diap. 10.'},

{id:'q204',m:'m15',d:'h',t:'mcq',
 q:'Un enunciado da: n₁ = 23 viviendas en Santiago con s₁ = 120 MM, y n₂ = 28 en Concepción con s₂ = 99,3 MM. Se pregunta si la <b>variabilidad</b> difiere. ¿Qué prueba y con qué grados de libertad?',
 o:['χ² con 50 gl','F con (22, 27) gl','t pooled con 49 gl','z, sin grados de libertad'],
 c:1,
 e:'Comparar la variabilidad de DOS poblaciones = prueba F, con gl = (n₁−1, n₂−1) = (22, 27). El primer gl corresponde al numerador. F = 120²/99.3² = 1.4603.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 54.'},

{id:'q205',m:'m15',d:'n',t:'mcq',
 q:'«Un experto considera que el <b>20%</b> de los fanáticos prefieren Cabernet. <b>30 de 200</b> lo eligen.» ¿Cuáles son p₀ y p̂?',
 o:['p₀ = 0.15 y p̂ = 0.20','p₀ = 0.20 y p̂ = 0.15','p₀ = 30 y p̂ = 200','p₀ = 0.20 y p̂ = 0.20'],
 c:1,
 e:'p₀ = 0.20 es el valor de la AFIRMACIÓN (va en H₀). p̂ = 30/200 = 0.15 es lo OBSERVADO en la muestra. Confundir cuál es cuál invierte el signo del estadístico.',
 s:'«Ejercicios preparación - Prueba 1», Problema 6.'},

{id:'q206',m:'m15',d:'h',t:'mcq',
 q:'«¿Se podría afirmar que el precio promedio <b>aumentó en más de $1.500</b>?» con datos de enero y abril. ¿Cuál es D₀ y cómo queda H₁?',
 o:['D₀ = 0 y H₁: μ₂ − μ₁ > 0','D₀ = 1500 y H₁: μ₂ − μ₁ > 1500','D₀ = 1500 y H₁: μ₂ − μ₁ ≠ 1500','D₀ = 1500 y H₁: μ₂ − μ₁ < 1500'],
 c:1,
 e:'«Aumentó en más de $1.500» fija la diferencia bajo H₀ en D₀ = 1500 y da una alternativa unilateral derecha: H₀: μ₂−μ₁ ≤ 1500 vs H₁: μ₂−μ₁ > 1500. En R: t.test(abril, enero, mu = 1500, alternative = "greater").',
 s:'PPT «2. Pruebas de Hipótesis», diap. 27 y 55.'},

{id:'q207',m:'m15',d:'n',t:'mcq',
 q:'Un enunciado dice «utilice un <b>nivel de confianza del 90%</b>». Para una prueba <b>bilateral</b>, ¿con qué valor buscas el valor crítico?',
 o:['α = 0.90','α = 0.10 y se busca con α/2 = 0.05','α = 0.10 sin dividir','α = 0.05 y se busca con 0.025'],
 c:1,
 e:'Confianza 90% ⟹ α = 1 − 0.90 = 0.10. Como es bilateral, el área se reparte entre dos colas ⟹ se busca el crítico con α/2 = 0.05 en cada una. Es el error de bulto nº3 de la lista.',
 s:'«Pauta Pregunta 3 - Prueba 1»; PPT diap. 13.'},

{id:'q208',m:'m15',d:'h',t:'mcq',
 q:'«Se afirma que la <b>desviación estándar</b> del grosor es de 0,1 mm.» Para la prueba χ², ¿cuál es σ₀²?',
 o:['0.1','0.01','0.001','0.316'], c:1,
 e:'El estadístico χ² = (n−1)s²/σ₀² usa VARIANZAS. El enunciado da la desviación, así que hay que elevarla al cuadrado: σ₀² = 0.1² = 0.01. Olvidarlo cambia el estadístico en un factor 10.',
 s:'«Ejercicios preparación - Prueba 1», Problema 8.'},

{id:'q209',m:'m15',d:'n',t:'mcq',
 q:'¿Cuántas condiciones hay que verificar antes de una prueba z para la <b>diferencia de dos proporciones</b>?',
 o:['Ninguna','Dos: np̂ ≥ 5 y n(1−p̂) ≥ 5','<b>Cuatro</b>: n₁p̂₁ ≥ 5, n₁q̂₁ ≥ 5, n₂p̂₂ ≥ 5, n₂q̂₂ ≥ 5','Una: n₁ + n₂ ≥ 30'],
 c:2,
 e:'Con dos poblaciones binomiales hay que verificar las cuatro condiciones que aparecen en la tabla resumen del PPT, dos por cada muestra. Con una sola población son dos.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 21 (tabla resumen de dos poblaciones).'},

{id:'q210',m:'m15',d:'h',t:'mcq',
 q:'En la diferencia de proporciones, ¿cuándo se usa la <b>proporción combinada</b> p̂ = (x₁+x₂)/(n₁+n₂)?',
 o:['Siempre, en todos los casos',
    'Cuando H₀ afirma que las proporciones son <b>iguales</b> (p₁ = p₂), porque bajo H₀ hay una sola proporción común',
    'Cuando los tamaños de muestra son iguales',
    'Cuando la diferencia bajo H₀ es distinta de cero'],
 c:1,
 e:'Es la misma lógica que pooled vs Welch en medias: se combina solo cuando H₀ afirma igualdad. Si H₀ propone una diferencia distinta de cero, las proporciones no son iguales bajo H₀ y cada muestra aporta su propio p̂ᵢq̂ᵢ/nᵢ.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 21.'},

{id:'q211',m:'m15',d:'n',t:'mcq',
 q:'Una salida de R muestra «<code>t = -7.781, df = 18.55</code>». ¿Qué prueba se corrió?',
 o:['t pooled con 18 gl','t de <b>Welch</b> (los gl decimales son su firma)','t pareada','Prueba z'],
 c:1,
 e:'Los grados de libertad no enteros solo aparecen en la prueba de Welch, cuya fórmula ajusta los gl para compensar varianzas desiguales. La pooled da siempre enteros (n₁+n₂−2) y la pareada también (n−1).',
 s:'PPT «2. Pruebas de Hipótesis», diap. 36; script del curso.'},

{id:'q212',m:'m15',d:'h',t:'mcq',
 q:'Solo con la salida «<code>F = 8.924, num df = 11, denom df = 9</code>», ¿cuáles eran los tamaños de muestra?',
 o:['n₁ = 11 y n₂ = 9','n₁ = 12 y n₂ = 10','n₁ = 10 y n₂ = 8','No se puede saber'],
 c:1,
 e:'En la prueba F los gl son (n₁−1, n₂−1). Si son (11, 9), entonces n₁ = 12 y n₂ = 10. Los grados de libertad son la huella dactilar del test: revelan el tamaño de muestra y qué prueba se corrió.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 26; script del curso.'},

{id:'q213',m:'m15',d:'n',t:'mcq',
 q:'En la salida de <code>var.test()</code>, ¿qué valor debe contener el intervalo de confianza para NO rechazar H₀?',
 o:['0','<b>1</b>, porque el parámetro es un cociente de varianzas','El valor de s₁²','α'],
 c:1,
 e:'var.test estima la RAZÓN σ₁²/σ₂², cuyo valor «sin diferencia» es 1. Buscar el 0 ahí es un error clásico: el 0 es el referente de las DIFERENCIAS (t.test, cor.test), no de los cocientes.',
 s:'Salida de var.test reproducida en PPT «2. Pruebas de Hipótesis», diap. 26.'},

{id:'q214',m:'m15',d:'h',t:'mcq',
 q:'Se contrasta H₀: μ ≤ 5.8 vs H₁: μ > 5.8 y el estadístico observado es <b>t = −0.74765</b>. ¿Qué se concluye sin mirar tablas?',
 o:['Se rechaza H₀ porque |t| es distinto de cero',
    'No se rechaza H₀: en una prueba de cola derecha un estadístico negativo nunca cae en la zona de rechazo (p > 0.5)',
    'Hay que tomar el valor absoluto y comparar con t(α, 9)',
    'El signo indica un error de cálculo'],
 c:1,
 e:'En una prueba unilateral derecha la zona de rechazo está en la cola derecha (valores grandes positivos). Un t negativo está en el extremo opuesto: el p-valor será mayor que 0.5. En la salida real p = 0.7631. Solo en las bilaterales se toma valor absoluto.',
 s:'«Pauta Pregunta 3 - Prueba 1», Anexo 1.'},

{id:'q215',m:'m15',d:'n',t:'mcq',
 q:'¿Cuáles son los grados de libertad del test de <b>Bartlett</b> con p = 6 variables y n = 30 observaciones?',
 o:['29','15','6','24'], c:1,
 e:'gl = p(p−1)/2 = 6·5/2 = 15. Bartlett usa el número de VARIABLES para los gl, no el de observaciones — aunque n sí entra en el estadístico χ² = −(n−1−(2p+5)/6)·ln|R|.',
 s:'«Ayudantía 1 2026-20 Enunciado», P3; PPT «1. Correlación», diap. 27–28.'},

{id:'q216',m:'m15',d:'h',t:'mcq',
 q:'En una prueba de <b>correlación</b> con n = 10 observaciones, ¿cuántos grados de libertad tiene el estadístico t?',
 o:['10','9','<b>8</b>','5'], c:2,
 e:'gl = n − 2 = 8. Es la única prueba t del curso que resta 2 en vez de 1, porque se estiman dos parámetros (la pendiente y el intercepto de la relación). La pauta lo usa explícitamente: t = 0.0793·√(8/(1−0.0793²)).',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso c.'},

{id:'q217',m:'m15',d:'n',t:'mcq',
 q:'«Una empresa afirma que como máximo el 15% de sus parabrisas no cumple. Muestra de 200, se observan 40 defectuosos.» ¿Cuál es el estadístico Z?',
 o:['1.98','2.50','1.41','0.05'], c:0,
 e:'p̂ = 40/200 = 0.20, p₀ = 0.15. Z = (0.20 − 0.15)/√(0.15·0.85/200) = 0.05/0.02525 = 1.98. Nota que el error estándar usa p₀ = 0.15 (el valor bajo H₀), NO p̂. Con z crítico 1.645 se rechaza H₀.',
 s:'«Ayudantía 2 2026-20 Enunciado», P1.'},

{id:'q218',m:'m15',d:'h',t:'mcq',
 q:'En el estadístico Z de una proporción, el error estándar √(p(1−p)/n) usa…',
 o:['p̂, la proporción muestral','<b>p₀</b>, el valor bajo H₀','el promedio de p̂ y p₀','cualquiera de los dos, da lo mismo'],
 c:1,
 e:'La distribución del estadístico se construye ASUMIENDO que H₀ es verdadera, así que el error estándar se calcula con p₀. Usar p̂ da un número distinto y es un error frecuente. (En un intervalo de confianza sí se usa p̂, porque ahí no hay H₀.)',
 s:'PPT «2. Pruebas de Hipótesis», diap. 13.'},

{id:'q219',m:'m15',d:'n',t:'multi',
 q:'Selecciona TODAS las señales de que las muestras son <b>pareadas</b>.',
 o:['«Se mide a los mismos 20 participantes antes y después»',
    '«Se registra el colesterol de 11 pacientes antes y después del tratamiento»',
    '«Los mismos 10 alumnos rindieron Matemáticas y Física»',
    '«Se seleccionan 25 pacientes para el tratamiento A y 30 para el B»'],
 c:[0,1,2],
 e:'Las tres primeras vinculan cada observación de un grupo con una del otro (mismo sujeto). La cuarta describe dos grupos de personas DISTINTAS: son independientes, y además n₁ ≠ n₂, lo que hace imposible el emparejamiento.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 33; «Ejercicios preparación - Prueba 1», Problemas 2, 5 y 14.'},

{id:'q220',m:'m15',d:'h',t:'mcq',
 q:'«Se desea evaluar si el programa aumenta los ingresos promedio» de 20 emprendedores medidos <b>antes y después</b>. ¿Cuántos grados de libertad?',
 o:['38 (= 20 + 20 − 2)','19 (= n − 1, con n = 20 pares)','40','18'], c:1,
 e:'En muestras pareadas n es el número de PARES, no el total de mediciones. Con 20 emprendedores medidos dos veces hay 20 pares ⟹ gl = 19. Responder 38 es tratar los datos como independientes, que es el error de fondo.',
 s:'«Ejercicios preparación - Prueba 1», Problema 14.'},

{id:'q221',m:'m15',d:'n',t:'mcq',
 q:'Un enunciado pide contrastar el <b>vector de medias</b> de 4 variables medidas en 28 árboles, usando 3 contrastes. ¿Qué distribución se usa para decidir?',
 o:['χ² con 3 gl','<b>F con (3, 25) gl</b>','t con 27 gl','Normal estándar'],
 c:1,
 e:'El T² de Hotelling se transforma a una F con (p, n−p) grados de libertad. Con q = 3 contrastes y n = 28: F(3, 25). La salida real fue T² = 20.74, F = 6.40, df = (3,25), p = 0.0023.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 47 y 53.'},

{id:'q222',m:'m15',d:'h',t:'mcq',
 q:'La pregunta dice: «¿cuál es la probabilidad de <b>no rechazar</b> la afirmación de que μ = 1 kg, <b>sabiendo que la media verdadera es 1,005</b> kg?». ¿Qué estás calculando y en qué media te centras?',
 o:['α, centrado en 1','<b>β</b> (error tipo II), centrado en <b>1.005</b>','La potencia, centrado en 1','El p-valor, centrado en 1.005'],
 c:1,
 e:'«No rechazar» + «la media verdadera es otra» = error tipo II = β. Los límites de la zona de no rechazo se calculan con μ₀ = 1, pero la PROBABILIDAD se evalúa bajo la distribución centrada en μ_real = 1.005. No recentrar es el error clásico.',
 s:'«Ayudantía 2 2026-20 Enunciado», P2(c).'},

{id:'q223',m:'m15',d:'n',t:'mcq',
 q:'¿Qué distingue a <b>σ</b> de <b>s</b> al leer un enunciado?',
 o:['σ es más grande que s',
    'σ es un valor poblacional / histórico / de la norma; s se calculó a partir de la muestra. Determina si usas z o t',
    'σ se usa en dos muestras y s en una',
    'Son intercambiables'],
 c:1,
 e:'«Se sabe que la desviación estándar de la máquina es 15 ml» → σ (dato del proceso) → prueba z. «La muestra de 13 puntos de venta tuvo s = $230» → s (estimado) → prueba t. Esta distinción decide el test completo.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 5 y 10.'},

{id:'q224',m:'m15',d:'h',t:'mcq',
 q:'H₀: μ = 200 con región de <b>aceptación</b> dada (191, 209), σ = 15, n = 9. ¿Cuál es la probabilidad de cometer error tipo I?',
 o:['0.05','0.0719','0.1151','0.8849'], c:1,
 e:'σ_x̄ = 15/√9 = 5. α = P(x̄<191 o x̄>209 | μ=200) = P(Z<−1.8) + P(Z>1.8) = 0.0359 + 0.0359 = 0.0719. Ojo: aquí α NO es 0.05 — la región venía impuesta por el enunciado, no elegida a partir de un α.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 41–42.'},

{id:'q225',m:'m15',d:'h',t:'mcq',
 q:'Con la misma máquina (σ = 15, n = 9, zona de aceptación 191–209), ¿cuál es β si la media verdadera es μ = 215?',
 o:['0.0719','<b>0.1151</b>','0.5000','0.8849'], c:1,
 e:'β = P(191 < x̄ < 209 | μ = 215) = P((191−215)/5 < Z < (209−215)/5) = P(−4.8 < Z < −1.2) = Φ(−1.2) − 0 = 0.1151. La potencia es 1 − 0.1151 = 0.8849. En R: pnorm(209,215,5) − pnorm(191,215,5).',
 s:'PPT «2. Pruebas de Hipótesis», diap. 41–42.'},

{id:'q226',m:'m15',d:'n',t:'mcq',
 q:'Un enunciado da dos tamaños de muestra (n₁ = 13, n₂ = 15) y dos desviaciones (s₁ = 230, s₂ = 445). ¿Qué te sugiere la enorme diferencia entre s₁ y s₂?',
 o:['Que hay que usar la prueba pareada',
    'Que las varianzas probablemente son diferentes → conviene la <b>t de Welch</b> (var.equal = FALSE)',
    'Que hay que usar la prueba z',
    'Que los datos no son normales'],
 c:1,
 e:'s₂/s₁ ≈ 1.9, así que la razón de varianzas es ~3.7. Formalmente se confirma con var.test, pero el curso además recomienda Welch por defecto salvo certeza de igualdad (Zimmerman, 2004). En este ejercicio el PPT usa exactamente Welch.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 27 y 37.'},

{id:'q227',m:'m15',d:'h',t:'multi',
 q:'De la salida «<code>Welch Two Sample t-test; t = -7.781, df = 18.55, p-value < 0.0001; mean of x 14.408, mean of y 16.470</code>», selecciona TODO lo que se puede afirmar.',
 o:['Se usó var.equal = FALSE','Se rechaza H₀ al 5%','El grupo y tiene media mayor que el grupo x','Las muestras son pareadas'],
 c:[0,1,2],
 e:'«Welch» y el df decimal confirman var.equal = FALSE. p < 0.0001 < 0.05 → se rechaza. Las medias muestrales (14.408 vs 16.470) indican que y es mayor, coherente con t negativo. NO son pareadas: una prueba pareada se titularía «Paired t-test» y mostraría «mean difference».',
 s:'PPT «2. Pruebas de Hipótesis», diap. 36.'},

{id:'q228',m:'m15',d:'n',t:'mcq',
 q:'El enunciado no menciona ninguna diferencia concreta: «¿existe evidencia de que el tratamiento A es más efectivo que el B?». ¿Cuánto vale D₀?',
 o:['1','<b>0</b>','Depende de las medias muestrales','No se puede saber'],
 c:1,
 e:'Si no se especifica una magnitud de diferencia, D₀ = 0 y las hipótesis son H₀: μ_A ≤ μ_B vs H₁: μ_A > μ_B. En R basta t.test(A, B, alternative = "greater"), porque mu = 0 es el valor por defecto.',
 s:'«Ejercicios preparación - Prueba 1», Problema 2.'},

{id:'q229',m:'m15',d:'h',t:'mcq',
 q:'Se obtiene t₀ = 2.247 en una prueba <b>bilateral</b> con 20 gl y α = 0.05. Los valores críticos son ±2.086. ¿Decisión?',
 o:['No se rechaza H₀, porque 2.247 < 2.845',
    'Se rechaza H₀, porque |2.247| > 2.086',
    'No se rechaza, porque hay que usar α = 0.05 y no α/2',
    'Se necesita el p-valor para decidir'],
 c:1,
 e:'En bilateral se compara el VALOR ABSOLUTO del estadístico con el crítico de α/2 = 0.025. Como 2.247 > 2.086, cae en la zona de rechazo. Este es el ejercicio de las líneas de llenado A y B de la pauta.',
 s:'«Pauta Pregunta 2 - Prueba 1», inciso b.'},

{id:'q230',m:'m15',d:'n',t:'mcq',
 q:'Se obtiene χ²₀ = 28.175 con 23 gl y el crítico es χ²(0.05, 23) = 35.172, en prueba unilateral derecha. ¿Decisión?',
 o:['Se rechaza H₀','<b>No se rechaza H₀</b>, porque 28.175 < 35.172','Se rechaza porque el estadístico es positivo','Falta el valor de α'],
 c:1,
 e:'En una prueba χ² unilateral derecha se rechaza solo si el estadístico SUPERA el crítico. 28.175 < 35.172 → no cae en la zona de rechazo → no hay evidencia de que σ > 2 minutos.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 18.'},

{id:'q231',m:'m15',d:'h',t:'mcq',
 q:'¿Cuál de estas comparaciones para decidir es <b>incorrecta</b>?',
 o:['Rechazo si p-valor ≤ α','Rechazo si el IC de t.test(x, mu=10) no contiene 10','Rechazo si el IC de var.test(A,B) no contiene 0','Rechazo si |t_obs| > t_{α/2, gl} en una prueba bilateral'],
 c:2,
 e:'var.test estima un COCIENTE de varianzas, cuyo valor de referencia es 1, no 0. Las otras tres son correctas. El 0 es el referente de las diferencias (t.test de dos muestras) y de las correlaciones (cor.test).',
 s:'Salidas de t.test y var.test en PPT «2. Pruebas de Hipótesis», diap. 8 y 26.'},

{id:'q232',m:'m15',d:'n',t:'mcq',
 q:'«Se toma una muestra de 24 estudiantes, con varianza muestral de 4,9 min², y se afirma que la desviación es máximo 2 minutos.» ¿Qué números van en χ² = (n−1)s²/σ₀²?',
 o:['n=24, s²=4.9, σ₀²=2','n=24, s²=4.9, σ₀²=4','n=23, s²=2, σ₀²=4.9','n=24, s²=2, σ₀²=4.9'],
 c:1,
 e:'n = 24 (la muestra), s² = 4.9 (lo observado), σ₀² = 2² = 4 (la afirmación, elevada al cuadrado). χ² = 23·4.9/4 = 28.175 con 23 gl.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 18.'},

{id:'q233',m:'m15',d:'h',t:'mcq',
 q:'«La media del consumo de la ciudad es 721 kWh. La junta cree que su barrio consume más. Muestra de 20 hogares.» Ubica los números.',
 o:['μ₀ = 721, n = 20, gl = 19, prueba t unilateral derecha',
    'x̄ = 721, n = 20, gl = 20, prueba z bilateral',
    'μ₀ = 721, n = 20, gl = 19, prueba z unilateral derecha',
    'μ₀ = 20, n = 721, gl = 720, prueba t'],
 c:0,
 e:'721 es el valor de la afirmación conocida → μ₀. n = 20 → gl = 19. «Consume más» → unilateral derecha. Se usa t porque el enunciado no da σ poblacional. Valor crítico t(0.05, 19) = 1.73; p = 0.02188 → se rechaza.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 5–6.'},

{id:'q234',m:'m15',d:'n',t:'mcq',
 q:'En la prueba F, ¿qué significa obtener F ≈ 1?',
 o:['Que las medias son iguales','Que las varianzas de las dos poblaciones son <b>similares</b>','Que hay un error de cálculo','Que se rechaza H₀'],
 c:1,
 e:'F = s₁²/s₂², así que F ≈ 1 significa que las dos varianzas muestrales son parecidas → no hay evidencia contra H₀: σ₁² = σ₂². Si F ≫ 1 o F ≪ 1, las varianzas son diferentes. La F no dice nada sobre las medias.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 22.'},

{id:'q235',m:'m15',d:'h',t:'mcq',
 q:'Un p-valor de <b>0.03</b>. ¿Con cuáles de estos α se rechazaría H₀?',
 o:['Solo con α = 0.01','Con α = 0.05 y α = 0.10, pero <b>no</b> con α = 0.01','Con los tres','Con ninguno'],
 c:1,
 e:'La regla es p ≤ α. 0.03 ≤ 0.05 ✓ y 0.03 ≤ 0.10 ✓, pero 0.03 > 0.01 ✗. Esto ilustra la definición del PPT: el valor P es el MÍNIMO nivel de significancia para el cual el estadístico resulta significativo.',
 s:'PPT «2. Pruebas de Hipótesis», lámina «Formas de tomar la decisión».'},

/* ═══════════ M4 · p-valor y decisión ═══════════ */
{id:'q240',m:'m4',d:'h',t:'mcq',
 q:'Según el PPT, «el valor P es el mínimo nivel de significancia para el cual el valor de la estadística de prueba es significativo». ¿De qué tres cosas depende el p-valor?',
 o:['Del tamaño de muestra, la media y la varianza',
    'De la distribución a utilizar, de la hipótesis alternativa H₁ y del valor del estadístico de prueba',
    'De α, de β y de la potencia',
    'Solo del estadístico de prueba'],
 c:1,
 e:'Son los tres factores que lista la lámina «Formas de tomar la decisión». Nota que H₁ importa: el mismo estadístico da un p-valor distinto según la prueba sea unilateral o bilateral (el bilateral es el doble).',
 s:'PPT «2. Pruebas de Hipótesis», lámina «Formas de tomar la decisión».'},

{id:'q241',m:'m4',d:'n',t:'mcq',
 q:'Según el PPT, si el valor P es <b>menor de 0.001</b>…',
 o:['no se puede concluir nada','se rechaza H₀ a cualquier nivel de significancia','se acepta H₀','hay un error de cálculo'],
 c:1,
 e:'Un p-valor muy pequeño es menor que cualquier α habitual (0.01, 0.05, 0.10), así que la decisión es rechazar en todos los casos. Simétricamente, si P > 0.1 no se rechaza a ningún nivel usual.',
 s:'PPT «2. Pruebas de Hipótesis», lámina «Formas de tomar la decisión».'},

{id:'q242',m:'m4',d:'h',t:'mcq',
 q:'En el ejemplo de la esperanza de vida: x̄ = 71.8, σ = 8.9, n = 100, μ₀ = 70. ¿Cuál es el estadístico?',
 o:['z = 2.02','t = 2.02','z = 0.20','z = 1.64'], c:0,
 e:'z = (x̄ − μ₀)/(σ/√n) = (71.8 − 70)/(8.9/√100) = 1.8/0.89 = 2.02. Es z y no t porque σ = 8.9 es un valor poblacional conocido. Con z crítico 1.64 y p = P(z>2.02) = 0.0217 ≤ 0.05, se rechaza H₀.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 3–4.'},

{id:'q243',m:'m4',d:'n',t:'mcq',
 q:'¿Cuál de estas afirmaciones sobre el p-valor es <b>falsa</b>?',
 o:['Es la probabilidad de obtener un resultado tan extremo o más que el observado, asumiendo H₀ verdadera',
    'Es el mínimo nivel de significancia al que el estadístico resulta significativo',
    '<b>Es la probabilidad de que H₀ sea verdadera</b>',
    'Si p ≤ α se rechaza H₀'],
 c:2,
 e:'El p-valor NO es la probabilidad de que H₀ sea verdadera: es una probabilidad calculada BAJO el supuesto de que H₀ es verdadera. Es el malentendido más extendido sobre las pruebas de hipótesis.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 14 y lámina «Formas de tomar la decisión».'},

{id:'q244',m:'m4',d:'h',t:'mcq',
 q:'Dos investigadores analizan los mismos datos. Uno plantea H₁: μ > μ₀ y obtiene p = 0.03. El otro plantea H₁: μ ≠ μ₀. ¿Qué p-valor obtiene el segundo?',
 o:['0.03','0.015','<b>0.06</b>','0.97'], c:2,
 e:'El p-valor bilateral es el doble del unilateral cuando el estadístico apunta en la dirección de la alternativa: 2 × 0.03 = 0.06. Con α = 0.05 el primero rechaza y el segundo no — el mismo dato, distinta conclusión. Por eso H₁ debe fijarse ANTES de ver los datos.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 14 (cálculo bilateral) y lámina «Formas de tomar la decisión».'},

{id:'q245',m:'m4',d:'n',t:'mcq',
 q:'En la tabla de tipos de errores del PPT, ¿qué celda corresponde a «No rechazar H₀ dado que H₀ es falsa»?',
 o:['Error tipo I','<b>Error tipo II</b>','Decisión correcta','Potencia'],
 c:1,
 e:'Error tipo I = rechazar H₀ dado que es verdadera (P = α). Error tipo II = no rechazar H₀ dado que es falsa (P = β). Las otras dos celdas de la tabla son decisiones correctas.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 39 (tabla «Tipos de errores (Riesgos)»).'},

/* ═══════════ M5 · una población, decisión numérica ═══════════ */
{id:'q250',m:'m5',d:'h',t:'mcq',
 q:'Salida: «<code>One Sample t-test; t = 1.5546, df = 9, p-value = 0.07723</code>» para H₀: μ ≤ 4 vs H₁: μ > 4, con α = 0.10. ¿Decisión?',
 o:['No se rechaza H₀','<b>Se rechaza H₀</b>, porque 0.07723 < 0.10','Se necesita el valor crítico','No se puede concluir con n = 10'],
 c:1,
 e:'p = 0.07723 ≤ α = 0.10 → se rechaza H₀. Con α = 0.05 la decisión habría sido la contraria. Es el inciso (d) de la pauta: con 10% hay evidencia de que la media en matemáticas supera 4.0.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso d y Anexo 1.'},

{id:'q251',m:'m5',d:'h',t:'mcq',
 q:'Salida: «<code>t.test(fisica, mu=5.8, alternative="greater"): t = -0.74765, df = 9, p-value = 0.7631</code>». ¿Qué concluye la pauta?',
 o:['Se rechaza H₀: la media de física supera 5.8',
    'No se rechaza H₀ ⟹ <b>la afirmación μ_fis ≤ 5.8 es cierta</b>',
    'Los datos no son normales',
    'Hay que repetir con α = 0.01'],
 c:1,
 e:'p = 0.7631 > 0.10 → no se rechaza H₀: μ ≤ 5.8. Como la afirmación de los profesores ERA precisamente μ_fis ≤ 5.8, no rechazar respalda esa afirmación. Ojo con el matiz: no se «demuestra» H₀, pero en este ejercicio la afirmación coincidía con H₀.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso d.'},

{id:'q252',m:'m5',d:'n',t:'mcq',
 q:'De <code>summary(matematicas)</code>: Min 2.800, 1st Qu. 4.050, Median 4.550, Mean 4.530, 3rd Qu. 4.775, Max 6.800. ¿Cuál es el IQR?',
 o:['4.000','<b>0.725</b>','0.505','2.245'], c:1,
 e:'IQR = Q₃ − Q₁ = 4.775 − 4.050 = 0.725. El rango total es Max − Min = 6.800 − 2.800 = 4.000. Ambos sirven para argumentar dispersión, pero son medidas distintas.',
 s:'«Pauta Pregunta 3 - Prueba 1», anexo de descriptivas.'},

{id:'q253',m:'m5',d:'h',t:'mcq',
 q:'Con Var(matemáticas) = 1.162 y Var(física) = 0.302, ¿cuál muestra tiene mayor dispersión y con qué otro enfoque se confirma?',
 o:['Física; se confirma con la media',
    'Matemáticas; se confirma con el IQR (0.725 vs 0.525) o con el rango (4.0 vs 1.9)',
    'Ambas igual',
    'No se puede comparar porque están en escalas distintas'],
 c:1,
 e:'Matemáticas: Var = 1.162 > 0.302, IQR = 4.775−4.050 = 0.725 > 5.850−5.325 = 0.525, y rango = 4.0 > 1.9. La rúbrica exigía DOS enfoques distintos, 0.25 pts cada uno.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso a y su rúbrica.'},

{id:'q254',m:'m5',d:'n',t:'mcq',
 q:'Con n = 12 y α = 0.05 en una prueba χ² unilateral derecha, ¿qué comando de R da el valor crítico?',
 o:['qchisq(0.05, 12)','<b>qchisq(0.95, 11)</b>','pchisq(0.95, 11)','qchisq(0.05, 11)'],
 c:1,
 e:'q = cuantil (valor crítico); para la cola derecha se pide el cuantil 1−α = 0.95; y gl = n−1 = 11. El resultado es 19.6751, el valor que usa la pauta de la Pregunta 2.',
 s:'«Pauta Pregunta 2 - Prueba 1»; script «2. Pruebas de Hipótesis. Ejemplos R».'},

{id:'q255',m:'m5',d:'h',t:'mcq',
 q:'Una prueba χ² <b>bilateral</b> con n = 10 y α = 0.05. ¿Cuántos valores críticos necesitas y cómo los obtienes?',
 o:['Uno solo: qchisq(0.95, 9)',
    'Dos, y NO son simétricos: qchisq(0.025, 9) y qchisq(0.975, 9), porque la χ² es asimétrica',
    'Dos simétricos: ±qchisq(0.975, 9)',
    'Ninguno, la χ² no admite pruebas bilaterales'],
 c:1,
 e:'La χ² está definida solo para valores positivos y es asimétrica, así que los dos cuantiles se buscan por separado. En la t y la normal basta cambiar el signo, pero aquí no.',
 s:'«Ayudantía 2 2026-20 Enunciado», P3(a); PPT diap. 17–20.'},

{id:'q256',m:'m5',d:'h',t:'mcq',
 q:'Se corre <code>prop.test(78, 120, 0.6, "greater", correct = FALSE)</code> y sale «X-squared = 1.25, p-value = 0.1318». Con α = 0.05, ¿decisión y por qué?',
 o:['Se rechaza H₀ porque X-squared > 1',
    'No se rechaza H₀: 0.1318 > 0.05, así que p̂ = 0.65 no difiere significativamente de 0.60',
    'Se rechaza porque p̂ = 0.65 > 0.60',
    'La prueba no es válida sin corrección de continuidad'],
 c:1,
 e:'La decisión se toma con el p-valor, no con la diferencia observada. Aunque p̂ = 0.65 > 0.60, esa diferencia es compatible con el azar dado n = 120. Nota que X² = z² = 1.118².',
 s:'PPT «2. Pruebas de Hipótesis», diap. 16.'},

{id:'q257',m:'m5',d:'n',t:'mcq',
 q:'Con n = 120 y p₀ = 0.60, ¿con qué números se verifica el requisito de la aproximación normal?',
 o:['120×0.65 y 120×0.35, usando p̂','<b>120×0.60 = 72 y 120×0.40 = 48</b>, usando p₀','120 y 0.60','78 y 42'],
 c:1,
 e:'El requisito np₀ ≥ 5 y n(1−p₀) ≥ 5 se verifica con p₀, el valor bajo H₀. Ambos (72 y 48) superan holgadamente 5, así que la aproximación normal es válida.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 12 y 43.'},

{id:'q258',m:'m5',d:'h',t:'mcq',
 q:'Un IC del 95% para la media resulta [9.994, 11.479] y se contrasta H₀: μ = 10. ¿Qué se concluye y por qué?',
 o:['Se rechaza H₀ porque la media muestral es 10.737',
    'No se rechaza H₀: el intervalo <b>contiene</b> el valor μ₀ = 10',
    'Se rechaza porque el intervalo es muy ancho',
    'El IC no sirve para decidir'],
 c:1,
 e:'Equivalencia test–IC: un IC bilateral de (1−α) contiene μ₀ ⟺ no se rechaza H₀: μ = μ₀ a nivel α. Aquí 10 ∈ [9.994, 11.479], lo que confirma el p = 0.0517 > 0.05. Por poco, pero no se rechaza.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 8.'},

{id:'q259',m:'m5',d:'n',t:'mcq',
 q:'Se obtiene «<code>z = 2.164, p-value = 0.0153, IC 95%: [10.189, Inf)</code>» para H₀: μ ≤ 10 vs H₁: μ > 10. ¿Cómo confirma el IC la decisión?',
 o:['El IC no aporta nada en pruebas unilaterales',
    'Como μ₀ = 10 queda <b>fuera</b> del intervalo (10 < 10.189), se confirma el rechazo',
    'Como el IC llega a infinito, siempre se rechaza',
    'Habría que calcular el IC bilateral'],
 c:1,
 e:'En la prueba unilateral derecha el IC tiene límite superior Inf y solo importa el límite inferior. Como 10 < 10.189, el valor bajo H₀ no es plausible → se rechaza, coherente con p = 0.0153 < 0.05.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 11.'},

/* ═══════════ M6 · dos poblaciones ═══════════ */
{id:'q265',m:'m6',d:'h',t:'mcq',
 q:'Grupo A: 45 éxitos de 120. Grupo B: 30 de 100. Se contrasta H₀: p₁ = p₂. ¿Cuál es la proporción combinada?',
 o:['0.375','0.300','<b>0.3409</b>','0.6591'], c:2,
 e:'p̂ = (x₁+x₂)/(n₁+n₂) = (45+30)/(120+100) = 75/220 = 0.3409. Se combina porque H₀ afirma que las proporciones son IGUALES: bajo H₀ hay una sola proporción común. No es el promedio simple de 0.375 y 0.300.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 21 (tabla resumen).'},

{id:'q266',m:'m6',d:'h',t:'mcq',
 q:'Con p̂₁ = 0.375 (n₁=120), p̂₂ = 0.300 (n₂=100) y p̂ combinada = 0.3409, el estadístico da z = 1.169 (p bilateral = 0.243). Con α = 0.05, ¿decisión?',
 o:['Se rechaza H₀: las proporciones difieren',
    'No se rechaza H₀: la diferencia de 7,5 puntos no es estadísticamente significativa con estos tamaños',
    'No se puede decidir sin el IC',
    'Se rechaza porque z > 1'],
 c:1,
 e:'p = 0.243 > 0.05 → no se rechaza. Una diferencia observada de 7.5 puntos porcentuales puede parecer grande, pero con n₁=120 y n₂=100 es compatible con el azar. En R: prop.test(c(45,30), c(120,100), correct = FALSE).',
 s:'Aplicación de la fórmula del PPT «2. Pruebas de Hipótesis», diap. 21.'},

{id:'q267',m:'m6',d:'n',t:'mcq',
 q:'¿Qué función de R compara <b>dos proporciones</b>?',
 o:['t.test(c(x1,x2), c(n1,n2))','<b>prop.test(c(x1, x2), c(n1, n2), correct = FALSE)</b>','var.test(p1, p2)','cor.test(p1, p2)'],
 c:1,
 e:'prop.test acepta vectores de éxitos y de tamaños. Con un solo par de números hace la prueba de una proporción; con dos, la de diferencia de proporciones. correct = FALSE desactiva la corrección de continuidad.',
 s:'Extensión de prop.test presentada en PPT «2. Pruebas de Hipótesis», diap. 16, y tabla de diap. 21.'},

{id:'q268',m:'m6',d:'h',t:'mcq',
 q:'La forma general del estadístico F del PPT es F = (σ₂²S₁²)/(σ₁²S₂²). ¿A qué se reduce bajo H₀: σ₁² = σ₂²?',
 o:['A F = S₂²/S₁²','A <b>F = S₁²/S₂²</b>, porque los σ² se cancelan','A F = 1 siempre','A F = σ₁²/σ₂²'],
 c:1,
 e:'Si σ₁² = σ₂², esos factores se cancelan y queda el cociente de varianzas muestrales. La forma general sirve cuando H₀ propone una razón de varianzas distinta de 1.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 21 (tabla resumen).'},

{id:'q269',m:'m6',d:'h',t:'mcq',
 q:'Un enunciado dice «suponga varianzas poblacionales iguales». ¿Qué implica para el cálculo?',
 o:['Hay que correr var.test primero',
    'Se usa la varianza combinada Sp² y gl = n₁+n₂−2 (t pooled)',
    'Se usa la fórmula de Welch',
    'No cambia nada'],
 c:1,
 e:'Cuando el enunciado lo declara explícitamente, no hace falta la prueba F previa: se va directo a la pooled. Sp² = [(n₁−1)s₁² + (n₂−1)s₂²]/(n₁+n₂−2) y gl = n₁+n₂−2. Es lo que hace la Pauta de la Pregunta 2.',
 s:'«Pauta Pregunta 2 - Prueba 1», inciso b.'},

{id:'q270',m:'m6',d:'h',t:'mcq',
 q:'Se calcula Sp² = 27 con n₁ = 10 y n₂ = 12. ¿Cuál es el error estándar de la diferencia de medias?',
 o:['√27 = 5.196','5.196 × √(1/10 + 1/12) = <b>2.225</b>','27 × (1/10 + 1/12) = 4.95','√(27/22) = 1.108'],
 c:1,
 e:'El error estándar es Sp·√(1/n₁ + 1/n₂) = 5.196·√0.1833 = 5.196·0.4282 = 2.225. Luego t₀ = (503−498)/2.225 = 2.247. Confundir Sp con el error estándar es un error frecuente: falta el factor √(1/n₁+1/n₂).',
 s:'«Pauta Pregunta 2 - Prueba 1», inciso b.'},

{id:'q271',m:'m6',d:'n',t:'mcq',
 q:'¿Qué encabezado muestra R cuando se corre <code>t.test(A, B, var.equal = TRUE)</code>?',
 o:['«Welch Two Sample t-test»','«Two Sample t-test» (sin la palabra Welch)','«Paired t-test»','«One Sample t-test»'],
 c:1,
 e:'El encabezado distingue las tres pruebas: «Two Sample t-test» = pooled; «Welch Two Sample t-test» = var.equal = FALSE; «Paired t-test» = paired = TRUE. Es lo primero que hay que mirar al interpretar una salida.',
 s:'Salidas reproducidas en PPT «2. Pruebas de Hipótesis», diap. 36–38.'},

{id:'q272',m:'m6',d:'h',t:'mcq',
 q:'En datos pareados con d = Antes − Después, se obtiene d̄ = 0.64 y t = 1.7281 con 9 gl. ¿Qué indica el signo positivo de d̄?',
 o:['Que «Después» es mayor que «Antes»','Que <b>«Antes» es mayor que «Después»</b> en promedio','Que hubo un error de orden','Nada, el signo es arbitrario'],
 c:1,
 e:'Si d = Antes − Después y d̄ > 0, entonces en promedio Antes > Después. En el ejemplo del colesterol eso significaba que el tratamiento REDUJO el colesterol. El PPT advierte explícitamente: «el orden importa».',
 s:'PPT «2. Pruebas de Hipótesis», diap. 38 y 57.'},

{id:'q273',m:'m6',d:'h',t:'multi',
 q:'Selecciona TODAS las formas equivalentes de contrastar H₀: μ_antes − μ_después ≤ 2 con datos pareados.',
 o:['t.test(antes - 2, despues, alternative = "greater", paired = TRUE)',
    't.test(antes, despues, mu = 2, alternative = "greater", paired = TRUE)',
    'Calcular manualmente t = (d̄ − 2)/(s_d/√n) y comparar con qt(1−α, n−1)',
    't.test(antes, despues, var.equal = TRUE, alternative = "greater")'],
 c:[0,1,2],
 e:'Las tres primeras son equivalentes: trasladar D₀ restando 2, indicarlo con mu = 2, o hacerlo a mano. La cuarta trata los datos como INDEPENDIENTES (var.equal en vez de paired), lo que cambia el estadístico y los gl.',
 s:'«Ayudantia 3 2026-20 Pauta R.R», Problema 5 (formas 1 y 2).'},

{id:'q274',m:'m6',d:'h',t:'mcq',
 q:'En el problema del limón se obtiene t = 0.928 con gl de Welch 21.56 ≈ 22 y crítico 1.72. ¿Cuál es la conclusión correcta de la pauta?',
 o:['El precio no aumentó',
    'Se demostró que el aumento fue ≤ $1.500',
    'No hay evidencia suficiente para afirmar que aumentó en más de $1.500, lo que NO significa que el aumento no lo haya sido',
    'Se rechaza H₀'],
 c:2,
 e:'0.928 < 1.72 → no se rechaza. La pauta insiste en el matiz: no rechazar no es demostrar H₀. Posibles causas del no rechazo: alta variabilidad o tamaño de muestra insuficiente.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 55.'},

{id:'q275',m:'m6',d:'n',t:'mcq',
 q:'¿Por qué el curso recomienda Welch por defecto?',
 o:['Porque siempre da p-valores menores',
    'Porque es más conservadora y segura; solo se asume igualdad de varianzas con certeza o fuerte evidencia (Zimmerman, 2004)',
    'Porque es la única implementada en R',
    'Porque no requiere normalidad'],
 c:1,
 e:'Welch ajusta los gl para compensar varianzas desiguales, lo que la hace robusta. Si las varianzas resultan iguales, Welch pierde muy poca potencia; si son distintas, la pooled da resultados inválidos. Por eso es el default de t.test().',
 s:'PPT «2. Pruebas de Hipótesis», diap. 37.'},

/* ═══════════ M7 · límites y β ═══════════ */
{id:'q280',m:'m7',d:'h',t:'mcq',
 q:'Con σ = 15 conocida y n = 9, ¿cuál es el error estándar de la media muestral?',
 o:['15','<b>5</b>','1.667','45'], c:1,
 e:'σ_x̄ = σ/√n = 15/√9 = 15/3 = 5. Es el número que se usa para estandarizar los límites de la región de aceptación. Dividir por n en vez de √n es un error muy frecuente.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 41–42.'},

{id:'q281',m:'m7',d:'h',t:'mcq',
 q:'Se pide «la probabilidad de <b>rechazar</b> la afirmación del experto si en realidad el 30% prefiere el Cabernet». ¿Qué estás calculando?',
 o:['α','β','<b>La potencia (1 − β)</b>','El p-valor'],
 c:2,
 e:'«Rechazar» + «la verdad es otra (p_real = 0.30 ≠ p₀ = 0.20)» = rechazar correctamente = POTENCIA. Si preguntaran por «no rechazar» en esa misma situación, sería β. La palabra clave es rechazar/no rechazar.',
 s:'«Ejercicios preparación - Prueba 1», Problema 6.'},

{id:'q282',m:'m7',d:'h',t:'mcq',
 q:'Al calcular la potencia de una prueba de proporciones con p₀ = 0.20 y p_real = 0.30, ¿qué error estándar usa cada paso?',
 o:['Ambos usan p₀',
    'Paso 1 (límites de p̂): usa <b>p₀ = 0.20</b>. Paso 2 (probabilidad): usa <b>p_real = 0.30</b>',
    'Ambos usan p_real','Ambos usan p̂ observado'],
 c:1,
 e:'Los límites describen la regla de decisión, que se construye bajo H₀ → p₀. La probabilidad se evalúa en el mundo real → p_real. Usar el mismo error estándar en los dos pasos es el error más común de estas preguntas.',
 s:'«Ejercicios preparación - Prueba 1», Problemas 6 y 7.'},

{id:'q283',m:'m7',d:'h',t:'mcq',
 q:'σ = 0.02 conocida, n = 20, H₀: μ = 1 bilateral, α = 0.05. ¿Cuáles son los límites de x̄ que NO rechazan H₀?',
 o:['[0.98, 1.02]','<b>[0.99123, 1.00877]</b>','[0.99560, 1.00440]','[0.96, 1.04]'],
 c:1,
 e:'se = 0.02/√20 = 0.004472; z_{0.025} = 1.96. Límites: 1 ± 1.96×0.004472 = 1 ± 0.008765. Con esos límites se calcula después β si la media real es 1.005.',
 s:'«Ayudantía 2 2026-20 Enunciado», P2(b).'},

{id:'q284',m:'m7',d:'h',t:'mcq',
 q:'Para H₀: σ² ≤ σ₀² unilateral derecha, ¿qué valores de s² <b>rechazan</b> H₀?',
 o:['s² > σ₀²·χ²_{1−α,n−1}/(n−1)','s² > σ₀²·(n−1)/χ²_{1−α,n−1}','s² > χ²_{1−α,n−1}','s² > σ₀² + χ²_{1−α,n−1}/(n−1)'],
 c:0,
 e:'De (n−1)s²/σ₀² > χ²_{1−α,n−1} se despeja s² > σ₀²·χ²_{1−α,n−1}/(n−1). En R: sigma2_0 * qchisq(1-alpha, n-1) / (n-1). Ojo con no invertir la fracción.',
 s:'«Ayudantía 2 2026-20 Enunciado», P3(b).'},

{id:'q285',m:'m7',d:'h',t:'mcq',
 q:'¿Por qué, si te centras erróneamente en μ₀ en el segundo paso del cálculo de β, obtienes 1 − α?',
 o:['Porque α y β siempre suman 1',
    'Porque la zona de no rechazo se construyó precisamente para dejar fuera una probabilidad α <b>bajo μ₀</b>: si vuelves a evaluar bajo μ₀ recuperas su complemento',
    'Porque β = 1 − α por definición',
    'Es una coincidencia numérica'],
 c:1,
 e:'La región de no rechazo tiene, por construcción, probabilidad 1−α cuando μ = μ₀. β solo tiene sentido evaluando esa misma región bajo μ_real. Si obtienes exactamente 1−α, es señal de que olvidaste recentrar.',
 s:'Derivación de la definición de β en PPT «2. Pruebas de Hipótesis», diap. 41.'},

{id:'q286',m:'m7',d:'h',t:'mcq',
 q:'Con la máquina de 200 ml (σ=15, n=9, zona 191–209), ¿cuál es la <b>potencia</b> para detectar μ = 215?',
 o:['0.0719','0.1151','<b>0.8849</b>','0.9281'], c:2,
 e:'Potencia = 1 − β = 1 − 0.1151 = 0.8849. La prueba detecta la descalibración a 215 ml el 88.5% de las veces. Fíjate que 0.0719 es α y 0.1151 es β: las tres cantidades aparecen en el mismo ejercicio y hay que no confundirlas.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 41–42.'},

{id:'q287',m:'m7',d:'h',t:'mcq',
 q:'Con n = 10, s = 0.5495, μ₀ = 5.8 y t(0.1; 9) = 1.383029, ¿cuál es el valor límite de x̄ que no rechaza H₀: μ ≤ 5.8?',
 o:['6.04','5.98','6.56','5.56'], c:0,
 e:'x̄ ≤ μ₀ + t·s/√n = 5.8 + 1.383029×(0.5495/√10) = 5.8 + 1.383029×0.17376 = 5.8 + 0.2403 = 6.04. Nota que s = √Var = √0.302 = 0.5495: la pauta daba la varianza, no la desviación.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso e.'},

{id:'q288',m:'m7',d:'n',t:'mcq',
 q:'En la tabla del anexo aparecen qt(0.9, 9) = 1.383029 y qt(0.95, 9) = 1.833113. Para una prueba unilateral derecha con <b>α = 0.10</b> y 9 gl, ¿cuál usas?',
 o:['1.833113','<b>1.383029</b>','2.821438','0.8834039'],
 c:1,
 e:'Para la cola derecha con α = 0.10 se pide el cuantil 1−α = 0.90 ⟹ qt(0.9, 9) = 1.383029. El 1.833113 correspondería a α = 0.05. Leer mal la fila de la tabla cambia todo el resultado.',
 s:'«Pauta Pregunta 3 - Prueba 1», tabla de valores críticos del anexo.'},

/* ═══════════ M2 · escalamiento nuevo ═══════════ */
{id:'q295',m:'m2',d:'n',t:'mcq',
 q:'¿Cuál es el único método de escalamiento del curso en que los valores transformados <b>suman exactamente 1</b>?',
 o:['Normalización min-máx','Normalización L2','<b>Softmax</b>','Escalamiento robusto'],
 c:2,
 e:'Softmax: wᵢ = e^{xᵢ}/Σⱼe^{xⱼ}, y por construcción Σwᵢ = 1. Por eso transforma los valores en pesos o probabilidades. L2 hace que la NORMA sea 1 (no la suma), y min-máx solo acota al rango [0,1].',
 s:'PPT «1. Correlación», lámina «OTROS MÉTODOS» (escalamiento).'},

{id:'q296',m:'m2',d:'h',t:'mcq',
 q:'En el <b>escalamiento por cuantiles</b> (wᵢ = i/n), si los datos son [5, 7, 8, 10], ¿cuál es el valor transformado del dato 8?',
 o:['0.8','<b>0.75</b>','0.5','8/30'], c:1,
 e:'Se ordenan de menor a mayor y se asigna la posición: 5→1, 7→2, 8→3, 10→4, con n = 4. Para el 8: w = i/n = 3/4 = 0.75. Este método conserva solo el ORDEN, así que es inmune a outliers.',
 s:'PPT «1. Correlación», lámina «OTROS MÉTODOS».'},

{id:'q297',m:'m2',d:'h',t:'mcq',
 q:'¿Cuál es la diferencia entre Softmax y la normalización L2?',
 o:['Son lo mismo con distinto nombre',
    'Softmax hace que los valores <b>sumen</b> 1; L2 hace que la <b>norma</b> (√Σx²) sea 1',
    'L2 hace que sumen 1 y Softmax que la norma sea 1',
    'Softmax solo funciona con valores positivos'],
 c:1,
 e:'Es la confusión más común entre ambos. Softmax → Σwᵢ = 1 (pesos/probabilidades). L2 → ‖w‖ = 1 (dirección del vector). Un vector puede tener norma 1 y que sus componentes no sumen 1, y viceversa.',
 s:'PPT «1. Correlación», láminas de escalamiento («OTROS MÉTODOS»).'},

{id:'q298',m:'m2',d:'n',t:'mcq',
 q:'Se necesita escalar una variable con outliers muy marcados y solo importa el <b>orden relativo</b> de las observaciones. ¿Qué método?',
 o:['Estandarización z-score','Min-máx','<b>Escalamiento por cuantiles</b>','Softmax'],
 c:2,
 e:'El escalamiento por cuantiles reemplaza cada dato por su posición relativa i/n, así que un outlier extremo solo ocupa la última posición y no distorsiona nada. El z-score y el min-máx son muy sensibles a valores extremos (el min-máx especialmente, porque usa el máximo y el mínimo).',
 s:'PPT «1. Correlación», láminas de escalamiento.'},

{id:'q299',m:'m2',d:'h',t:'mcq',
 q:'Según el PPT, si X e Y son vectores <b>centrados</b>, ¿a qué equivale el producto punto X·Y?',
 o:['A corr(X, Y)','A <b>n · cov(X, Y)</b>','A la distancia euclídea','A ‖X‖·‖Y‖'],
 c:1,
 e:'Para vectores centrados: X·Y = Σ(xᵢ−x̄)(yᵢ−ȳ) = (n−1)·cov muestral, que el PPT escribe como n·cov. Y además cos(X,Y) = corr(X,Y). Producto punto, covarianza y correlación son la misma idea en distintas normalizaciones.',
 s:'PPT «1. Correlación», lámina «MEDIDAS DE SIMILITUD ENTRE VECTORES».'},

{id:'q300',m:'m2',d:'n',t:'multi',
 q:'Selecciona TODOS los métodos de escalamiento que aparecen en el PPT del curso.',
 o:['Estandarización (z-score)','Normalización min-máx','Escalamiento robusto','Normalización L2','Escalamiento por cuantiles','Softmax'],
 c:[0,1,2,3,4,5],
 e:'Son los SEIS. Los dos últimos aparecen en la lámina «OTROS MÉTODOS» y son los que más se olvidan al repasar. Cuantiles: wᵢ = i/n. Softmax: wᵢ = e^{xᵢ}/Σe^{xⱼ}.',
 s:'PPT «1. Correlación», diap. 40–45.'},

/* ═══════════ M10 · mtcars con números reales ═══════════ */
{id:'q305',m:'m10',d:'h',t:'mcq',
 q:'En mtcars, <code>summary(pca)</code> da Standard deviation PC1 = 2.5707 y PC2 = 1.6280. ¿Cuántos componentes retiene el criterio de <b>Kaiser</b>?',
 o:['1','<b>2</b>','3','11'], c:1,
 e:'λ₁ = 2.5707² = 6.608 > 1 ✓ y λ₂ = 1.6280² = 2.650 > 1 ✓, pero λ₃ = 0.79196² = 0.627 < 1 ✗. Retiene 2. Recuerda elevar al cuadrado: la fila del summary es √λ, no λ.',
 s:'Salida de summary(prcomp(mtcars, scale.=TRUE)) en PPT «3. ACP», diap. 21.'},

{id:'q306',m:'m10',d:'h',t:'mcq',
 q:'En mtcars, la Cumulative Proportion es PC1 = 0.6008 y PC2 = 0.8417. ¿Cuántos componentes exige el criterio del <b>80%</b>?',
 o:['1','<b>2</b>, porque PC1+PC2 = 84.17% ≥ 80%','3','No se alcanza el 80%'],
 c:1,
 e:'PC1 solo llega a 60.08%, insuficiente. Con PC2 se acumula 84.17%, que supera el 80%. En mtcars los tres criterios (Kaiser, codo y 80%) coinciden en 2 componentes — a diferencia del caso de la Ayudantía 2, donde discrepan.',
 s:'Salida de summary(prcomp(mtcars, scale.=TRUE)) en PPT «3. ACP», diap. 21.'},

{id:'q307',m:'m10',d:'h',t:'mcq',
 q:'En un ACP sobre la matriz de <b>correlación</b> de mtcars (11 variables), ¿cuánto debe sumar el conjunto de los 11 autovalores?',
 o:['1','<b>11</b>','32','No hay una suma fija'],
 c:1,
 e:'Con la matriz de correlación cada variable estandarizada aporta varianza 1, así que Σλₖ = traza(R) = p = 11. Verificación: λ₁ = 6.608 corresponde a 6.608/11 = 60.08%, que coincide con la Proportion of Variance de la salida.',
 s:'PPT «3. ACP», diap. 15; «Ayudantía 3 2026-20 Enunciado», P1(g).'},

{id:'q308',m:'m10',d:'h',t:'mcq',
 q:'En PC2 de mtcars los loadings son qsec = −0.4634, am = 0.4294, gear = 0.4623 y carb = 0.4136. Aplicando la regla del curso, ¿cómo se clasifican?',
 o:['Todas irrelevantes (< 0.5)','Todas <b>fuertes</b>, porque |loading| ≥ 0.40','Solo gear es fuerte','Solo las positivas cuentan'],
 c:1,
 e:'La regla del curso es |loading| ≥ 0.30 relevante y ≥ 0.40 fuerte. Las cuatro superan 0.40. El signo se lee aparte: qsec negativo frente a am/gear/carb positivos define el contraste «configuración deportiva vs desempeño en aceleración».',
 s:'PPT «3. ACP», diap. 22 y 24; salida de pca$rotation.'},

{id:'q309',m:'m10',d:'h',t:'mcq',
 q:'En la Ayudantía 2 (clientes) los criterios discrepan: Kaiser y codo dan 1 componente, el 80% exige 3. ¿Cuál es la mejor respuesta en una prueba?',
 o:['Elegir siempre Kaiser porque es el más objetivo',
    'Reportar explícitamente la discrepancia, justificar cada criterio y argumentar la elección (con λ₂ = 0.982, retener 2 es un compromiso defendible)',
    'Retener siempre 3 porque el 80% es la regla oficial',
    'Descartar el análisis'],
 c:1,
 e:'La pregunta pedía los tres criterios precisamente para que se vea que no siempre coinciden — algo típico con n = 5. La respuesta completa nombra los tres resultados, señala la discrepancia y toma partido con justificación. λ₂ = 0.982 queda a un pelo de 1.',
 s:'«Ayudantía 2 2026-20 Enunciado», P5(a).'},

{id:'q310',m:'m10',d:'h',t:'mcq',
 q:'¿Qué guardan <code>pca$center</code> y <code>pca$scale</code>?',
 o:['Los autovalores y autovectores',
    'Las <b>medias</b> y <b>desviaciones estándar</b> usadas al estandarizar, necesarias para puntuar casos nuevos',
    'Los scores de cada observación',
    'Los límites del biplot'],
 c:1,
 e:'Son los estadísticos del ajuste original. Para puntuar un caso nuevo hay que estandarizarlo con ESTOS valores: z = (nuevo − pca$center)/pca$scale, y luego aplicar los loadings. predict(pca, newdata) lo hace automáticamente.',
 s:'Procedimiento requerido en «Ayudantía 2 2026-20 Enunciado», P5(d).'},

{id:'q311',m:'m10',d:'n',t:'mcq',
 q:'En el ACP de las notas (Ayudantía 3), PC1 tiene varianza 3.87 y PC2 tiene 0.84. ¿Qué retiene Kaiser?',
 o:['Ninguno','<b>Solo PC1</b>, porque 0.84 < 1','Los dos','Los seis'],
 c:1,
 e:'Solo λ₁ = 3.87 supera 1; λ₂ = 0.84 no. La pauta además señala que el codo aparece entre PC1 y PC2, y que PC1 se interpreta como la «nota general» del alumno.',
 s:'«Ayudantia 3 2026-20 Pauta R.R», bloque 3.'},

{id:'q312',m:'m10',d:'h',t:'mcq',
 q:'Con 6 asignaturas y ACP sobre la matriz de correlación, PC1 tiene λ = 3.87. ¿Qué porcentaje de varianza explica?',
 o:['38.7%','<b>64.5%</b>','3.87%','87%'], c:1,
 e:'Con la matriz de correlación Σλ = p = 6. Proporción = 3.87/6 = 0.645 → 64.5%. Este es el paso que conecta el autovalor con la Proportion of Variance del summary.',
 s:'«Ayudantia 3 2026-20 Pauta R.R», bloques 2–3; regla del PPT «3. ACP», diap. 15.'},

/* ═══════════ M11–M12 · AF con salidas reales ═══════════ */
{id:'q320',m:'m11',d:'h',t:'mcq',
 q:'<code>KMO(datos)</code> sobre USArrests da Overall MSA = 0.65 y MSA individuales: Murder 0.62, Assault 0.64, UrbanPop 0.50, Rape 0.78. ¿Qué se concluye?',
 o:['El AF no es aplicable',
    'El KMO global (0.65) supera el 0.6 exigido, pero <b>UrbanPop está en el límite</b> (0.50) y es candidata a eliminarse',
    'Todas las variables son adecuadas',
    'Hay que aumentar el número de factores'],
 c:1,
 e:'El KMO se lee a dos niveles. Global 0.65 > 0.6 → adecuado (aunque solo «mediocre» en la escala de Kaiser). UrbanPop con MSA = 0.50 está justo en el borde de lo inaceptable, coherente con que sea la única variable que no es una tasa de criminalidad.',
 s:'Salida de KMO en PPT «4.2 Análisis Factorial», diap. 41.'},

{id:'q321',m:'m11',d:'h',t:'mcq',
 q:'<code>cortest.bartlett(datos)</code> sobre USArrests devuelve $chisq = 88.29, $p.value = 6.87e-17, $df = 6. ¿Por qué df = 6?',
 o:['Porque n = 50 y 50/6 ≈ 8','Porque p(p−1)/2 = 4·3/2 = 6, con p = 4 variables','Porque hay 6 pares de datos','Porque se extrajeron 6 factores'],
 c:1,
 e:'Los gl de Bartlett son p(p−1)/2, con p el número de VARIABLES. USArrests tiene 4 (Murder, Assault, UrbanPop, Rape) → 4·3/2 = 6. El p-valor de 6.87×10⁻¹⁷ rechaza contundentemente H₀: R = I.',
 s:'Salida en PPT «4.2 Análisis Factorial», diap. 42.'},

{id:'q322',m:'m12',d:'h',t:'mcq',
 q:'En USArrests, con Varimax h² = (0.90, 0.80, 0.45, 0.66). ¿Qué valores tiene h² con <b>Promax</b>?',
 o:['Cambian, porque cambian las cargas','Los <b>mismos</b>: (0.90, 0.80, 0.45, 0.66)','Se duplican','No se pueden calcular en rotación oblicua'],
 c:1,
 e:'Es la demostración numérica de la propiedad: la rotación NO cambia comunalidades, unicidades ni varianza total explicada. Lo que sí cambia son las cargas individuales (Murder pasa de 0.95 a 1.04) y el reparto entre factores (SS 1.95/0.86 → 2.03/0.78).',
 s:'Salidas de fa(rotate="varimax") y fa(rotate="promax") en PPT «4.2», diap. 43–44.'},

{id:'q323',m:'m12',d:'h',t:'mcq',
 q:'Varimax da Cumulative Var = 0.70 y Promax también da 0.70 en USArrests. ¿Qué demuestra?',
 o:['Que ambas rotaciones son idénticas',
    'Que la <b>varianza total explicada</b> por el conjunto de factores no cambia al rotar',
    'Que hay un error en la salida',
    'Que solo se necesita 1 factor'],
 c:1,
 e:'La rotación redistribuye la varianza entre factores (Proportion Var pasa de 0.49/0.21 a 0.51/0.19) pero el total explicado sigue siendo 0.70. Es exactamente lo que enuncia la lámina «¿Por qué rotar los factores?».',
 s:'PPT «4.2 Análisis Factorial», diap. 36, 43 y 44.'},

{id:'q324',m:'m12',d:'h',t:'mcq',
 q:'En la salida de Promax, Murder tiene carga <b>1.04</b>, mayor que 1. ¿Es un error?',
 o:['Sí, las cargas nunca superan 1',
    'No: en rotación <b>oblicua</b> la pattern matrix contiene coeficientes de regresión, no correlaciones, y pueden superar 1',
    'Sí, indica que el modelo no convergió',
    'No, porque las cargas se miden en la escala original'],
 c:1,
 e:'En rotación ortogonal las cargas SÍ son correlaciones y están acotadas en [−1,1]. En oblicua, la pattern matrix da coeficientes de regresión parcial de la variable sobre factores correlacionados, que pueden exceder 1. Es una diferencia conceptual, no un fallo.',
 s:'Salida de fa(rotate="promax") en PPT «4.2 Análisis Factorial», diap. 44.'},

{id:'q325',m:'m12',d:'h',t:'mcq',
 q:'Solo la salida de <b>Promax</b> incluye la sección «With factor correlations of: MR1–MR2 = 0.47». ¿Por qué no aparece en Varimax?',
 o:['Porque psych no la calcula en Varimax',
    'Porque Varimax es <b>ortogonal</b>: los factores son independientes por construcción y su correlación es 0',
    'Porque Varimax usa un método de extracción distinto',
    'Porque en Varimax los factores no están definidos'],
 c:1,
 e:'La rotación ortogonal fuerza correlación cero entre factores, así que informarla sería redundante. La oblicua la permite y por eso la reporta: aquí «criminalidad violenta» y «urbanización» correlacionan 0.47.',
 s:'PPT «4.2 Análisis Factorial», diap. 36–38 y 44.'},

{id:'q326',m:'m12',d:'h',t:'mcq',
 q:'La salida de fa() con USArrests dice «df of the model are <b>−1</b>» y RMSR = 0, Chi Square = 0, prob = NA. ¿Qué significa?',
 o:['El ajuste es perfecto y el modelo es excelente',
    'Con p = 4 variables y m = 2 factores los gl son [(4−2)²−6]/2 = −1: el modelo está <b>no identificado</b> y el ajuste «perfecto» es trivial, por lo que el test de bondad no se puede calcular',
    'Hay datos faltantes',
    'Hace falta rotar los factores'],
 c:1,
 e:'Los gl del modelo factorial son [(p−m)² − (p+m)]/2. Con p=4 y m=2 sale −1: hay más parámetros que ecuaciones. Por eso RMSR = 0 y prob = NA. Lección práctica: con 4 variables, 2 factores son demasiados.',
 s:'Salida de fa() en PPT «4.2 Análisis Factorial», diap. 43–44.'},

{id:'q327',m:'m12',d:'h',t:'mcq',
 q:'La salida dice «Factor Analysis using method = <b>minres</b>» y las columnas se llaman MR1, MR2. ¿Qué indica?',
 o:['Que se usó máxima verosimilitud',
    'Que se usó el método de <b>residuo mínimo</b>, el default de psych cuando no se especifica fm',
    'Que se usaron 2 rotaciones',
    'Que las variables están mal escaladas'],
 c:1,
 e:'El prefijo de las columnas revela el método de extracción: MR = minres, ML = máxima verosimilitud, PA = ejes principales. El PPT llama a fa() sin fm, así que usa el default minres; la pauta de la Ayudantía 3 sí pone fm = "ml" y sus columnas se llaman ML1/ML2.',
 s:'Salidas comparadas: PPT «4.2», diap. 43 vs «Ayudantia 3 2026-20 Pauta R.R», bloque 7.'},

{id:'q328',m:'m12',d:'h',t:'mcq',
 q:'En USArrests con Varimax: Murder 0.95, Assault 0.84, Rape 0.59 en MR1; UrbanPop 0.67 y Rape 0.56 en MR2. ¿Cómo se nombran los factores?',
 o:['MR1 «urbanización», MR2 «criminalidad»',
    'MR1 <b>«criminalidad violenta»</b>, MR2 <b>«urbanización»</b>',
    'Ambos miden lo mismo',
    'No son interpretables'],
 c:1,
 e:'MR1 agrupa los tres delitos violentos (49% de la varianza); MR2 está dominado por UrbanPop (21%). Rape carga en ambos (com = 2.0), lo que la hace la variable más difícil de asignar. UrbanPop tiene la h² más baja (0.45), coherente con su MSA bajo en el KMO.',
 s:'Salida de fa(datos, nfactors=2, rotate="varimax") en PPT «4.2», diap. 43.'},

{id:'q329',m:'m12',d:'h',t:'mcq',
 q:'En USArrests, la variable <b>Rape</b> tiene cargas 0.59 y 0.56 y <b>com = 2.0</b>. ¿Cómo se interpreta?',
 o:['Está perfectamente explicada por un solo factor',
    'Carga en <b>ambos</b> factores casi por igual, alejándose de la estructura simple ideal (com ≈ 1)',
    'Tiene comunalidad 2','Debe eliminarse del análisis'],
 c:1,
 e:'La complejidad indica cuántos factores influyen en la variable. com = 2.0 significa que depende esencialmente de dos, lo que la vuelve ambigua de interpretar. El ideal de la estructura simple de Thurstone es com ≈ 1.',
 s:'Salida de fa() en PPT «4.2», diap. 43; escala de com en «Ayudantia 3 2026-20 Pauta R.R».'},

{id:'q330',m:'m12',d:'h',t:'mcq',
 q:'En USArrests, UrbanPop tiene h² = 0.45 y u² = 0.55. ¿Qué significa?',
 o:['Está bien representada por los factores',
    'Solo el 45% de su varianza es explicada por los factores; el 55% es varianza específica + error',
    'Tiene una correlación de 0.45 con el factor 1',
    'Hay un error porque h² + u² debe dar 2'],
 c:1,
 e:'h² + u² = 1 (0.45 + 0.55 ✓). Una comunalidad de 0.45 es baja: la variable no comparte mucha estructura con las demás. Coincide con su MSA de 0.50 en el KMO — dos indicadores independientes señalando lo mismo.',
 s:'Salida de fa() en PPT «4.2», diap. 43; concepto en diap. 44.'},

{id:'q331',m:'m11',d:'h',t:'mcq',
 q:'Según la escala de Kaiser, un Overall MSA de <b>0.65</b> se califica como…',
 o:['Marvelous (excelente)','Meritorious (muy bueno)','<b>Mediocre</b> (marginal), aunque supera el umbral de 0.6 del curso','Unacceptable'],
 c:2,
 e:'Escala de Kaiser: 0.90+ marvelous · 0.80+ meritorious · 0.70+ middling · 0.60+ mediocre · 0.50+ miserable · <0.50 unacceptable. 0.65 cae en «mediocre»: usable, pero no ideal. Compáralo con el 0.82 de las notas de la Ayudantía 3, que sí es «meritorious».',
 s:'Salida del PPT «4.2», diap. 41; escala de Kaiser vía búsqueda en internet (Wikipedia, KMO test).'},

/* ═══════════ M1, M3, M8, M9, M13, M14 · refuerzos ═══════════ */
{id:'q340',m:'m1',d:'h',t:'mcq',
 q:'Se sabe que σ₁² = 16, ρ = −0.75 y det(Σ) = 7 para un vector bidimensional. Usando Cov(X₁,X₂) = ρσ₁σ₂, ¿cuánto vale σ₂²?',
 o:['<b>1</b>','4','7','16'], c:0,
 e:'det(Σ) = σ₁²σ₂² − (ρσ₁σ₂)² = σ₁²σ₂²(1 − ρ²). Sustituyendo: 7 = 16·σ₂²·(1 − 0.75²) = 16·σ₂²·0.4375 = 7·σ₂² ⟹ σ₂² = 1. Verificación: Σ = [[16, −3],[−3, 1]], det = 16 − 9 = 7 ✓ (σ₁₂ = −0.75·4·1 = −3).',
 s:'«Ejercicios preparación - Prueba 1», Problema 12; parametrización Σ = [[σ₁², ρσ₁σ₂],[ρσ₁σ₂, σ₂²]] del PPT «1. Correlación», diap. 35.'},

{id:'q341',m:'m1',d:'h',t:'mcq',
 q:'¿Cuál de estas matrices <b>NO</b> puede ser matriz de covarianzas?',
 o:['[[4, −3], [−3, 9]]','<b>[[1, 2], [2, 1]]</b>','[[9, 6], [6, 4]]','Todas pueden serlo'],
 c:1,
 e:'[[1,2],[2,1]] tiene det = 1 − 4 = −3 < 0, así que no es semidefinida positiva (sus autovalores son 3 y −1). [[4,−3],[−3,9]] tiene det = 27 > 0 ✓. [[9,6],[6,4]] tiene det = 0: es semidefinida positiva (caso degenerado con correlación perfecta ρ = 1), así que sí puede serlo.',
 s:'«Ejercicios preparación - Prueba 1», Problema 13.'},

{id:'q342',m:'m1',d:'h',t:'mcq',
 q:'La matriz [[0, 1], [1, 4]] ¿puede ser matriz de covarianzas?',
 o:['Sí, porque es simétrica',
    'No: una varianza de 0 exige que esa variable sea constante, y entonces su covarianza con cualquier otra debe ser 0, no 1 (además det = −1 < 0)',
    'Sí, si las variables están estandarizadas',
    'Solo si n > 30'],
 c:1,
 e:'Var(X₁) = 0 significa que X₁ no varía; una constante no puede covariar con nada. Formalmente, det = 0·4 − 1² = −1 < 0, así que no es semidefinida positiva.',
 s:'«Ejercicios preparación - Prueba 1», Problema 13.'},

{id:'q343',m:'m3',d:'h',t:'mcq',
 q:'Para una normal bivariada, la matriz se parametriza como Σ = [[σ₁², ρσ₁σ₂], [ρσ₁σ₂, σ₂²]]. Si σ₁ = 3, σ₂ = 2 y ρ = 0.5, ¿cuál es Cov(X₁, X₂)?',
 o:['0.5','<b>3</b>','6','1.5'], c:1,
 e:'Cov(X₁,X₂) = ρ·σ₁·σ₂ = 0.5 × 3 × 2 = 3. Es la fórmula que permite construir Σ cuando el enunciado da desviaciones y correlación en vez de covarianzas directamente.',
 s:'PPT «1. Correlación», diap. 35 (caso bivariado).'},

{id:'q344',m:'m8',d:'h',t:'mcq',
 q:'El T² de Hotelling con datos cork da «T² = 20.74, F = 6.40, df = (3,25), p = 0.0023». Con α = 0.01, ¿decisión?',
 o:['No se rechaza H₀','<b>Se rechaza H₀</b>, porque 0.0023 < 0.01','Se necesita el valor de T² crítico','No se puede decidir con p < 0.01'],
 c:1,
 e:'p = 0.0023 < 0.01 → se rechaza incluso al 1%. Equivalentemente, F = 6.40 > F₀.₀₁(3,25) = 4.68. Se concluye que el depósito de corteza NO es igual en las 4 direcciones.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 53.'},

{id:'q345',m:'m8',d:'h',t:'mcq',
 q:'Tras rechazar el T², los IC simultáneos son: (N+S)−(E+W) = [2.18, 15.53], N−S = [−3.83, 5.55], E−W = [−4.98, 6.98]. ¿Qué contraste explica el rechazo?',
 o:['N−S','E−W','<b>(N+S)−(E+W)</b>, porque es el único que no contiene el 0','Los tres por igual'],
 c:2,
 e:'Un IC que no contiene el 0 indica un contraste significativamente distinto de cero. Los otros dos contienen el 0, así que dentro de cada eje no hay diferencia. La diferencia está entre el eje norte-sur y el este-oeste.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 53.'},

{id:'q346',m:'m9',d:'h',t:'mcq',
 q:'Para S = [[2.333, 0.333], [0.333, 2.333]] los autovalores son 2.666 y 2.000. ¿Cómo verificas que están bien?',
 o:['Comprobando que su producto sea 1',
    'Comprobando que su <b>suma</b> (4.666) sea igual a la <b>traza</b> de S (2.333 + 2.333)',
    'Comprobando que sean menores que 1',
    'No hay forma de verificarlo'],
 c:1,
 e:'Σλₖ = traza(S) siempre. Aquí 2.666 + 2.000 = 4.666 = 2.333 + 2.333 ✓. Otra verificación: el producto de los autovalores es el determinante (2.666×2 = 5.332 = 2.333² − 0.333² ✓). Son dos comprobaciones rápidas y gratis en la prueba.',
 s:'PPT «3. ACP», diap. 17 (ejemplo numérico).'},

{id:'q347',m:'m13',d:'h',t:'mcq',
 q:'¿Qué se pone en la <b>diagonal</b> de la matriz analizada en cada técnica (con variables estandarizadas)?',
 o:['ACP: comunalidades · AF: unos',
    'ACP: <b>unos</b> (toda la varianza) · AF: la <b>comunalidad estimada</b> (menor que 1)',
    'Ambas usan ceros',
    'Ambas usan los autovalores'],
 c:1,
 e:'Es la diferencia técnica de la que se derivan todas las demás: el ACP analiza la varianza TOTAL, el AF solo la varianza COMPARTIDA. Por eso el AF necesita estimar comunalidades iterativamente y el ACP no.',
 s:'Búsqueda en internet (Universitat de València, Minitab); coherente con la descomposición 1 = h² + u² del PPT «4.2».'},

{id:'q348',m:'m14',d:'h',t:'mcq',
 q:'En la Pauta Pregunta 3, ¿por qué la comparación Física vs Matemáticas se hizo con <code>paired = TRUE</code>?',
 o:['Porque ambas muestras tienen n = 10',
    'Porque son los <b>mismos 10 alumnos</b> los que rindieron ambas asignaturas: cada nota de Física está vinculada a una de Matemáticas',
    'Porque las varianzas son distintas',
    'Porque las notas no son normales'],
 c:1,
 e:'El vínculo es el alumno. Tratar los datos como independientes daría gl = 18 en vez de 9 y un estadístico distinto. La rúbrica daba 0.2 puntos solo por escribir el código correcto de R.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso g y Anexo 2.'},

{id:'q349',m:'m14',d:'h',t:'mcq',
 q:'La afirmación es «μ_mat > 4 <b>O BIEN</b> μ_fis ≤ 5.8». Los resultados: para matemáticas se rechaza H₀ (p=0.077<0.10), para física no se rechaza (p=0.763). ¿La afirmación global es válida?',
 o:['No, porque una de las dos pruebas no rechazó',
    'Sí: ambas afirmaciones resultaron ciertas, y con una disyunción basta con que se cumpla al menos una',
    'No se puede concluir',
    'Solo si se corrige por comparaciones múltiples'],
 c:1,
 e:'Rechazar H₀: μ_mat ≤ 4 confirma que μ_mat > 4 ✓. No rechazar H₀: μ_fis ≤ 5.8 respalda que μ_fis ≤ 5.8 ✓. Como es un «o bien», bastaba una; aquí se cumplen las dos, así que la afirmación global es cierta.',
 s:'«Pauta Pregunta 3 - Prueba 1», inciso d.'},

{id:'q350',m:'m14',d:'n',t:'multi',
 q:'Según la tabla de decisión, ¿cuáles de estos caminos llevan a la MISMA conclusión?',
 o:['Comparar el p-valor con α','Comparar el estadístico con el valor crítico','Ver si el IC contiene el valor bajo H₀','Comparar la media muestral con la media poblacional a ojo'],
 c:[0,1,2],
 e:'Los tres primeros son formalmente equivalentes y siempre coinciden. El cuarto no es un criterio: una diferencia observada puede parecer grande y no ser significativa (p̂ = 0.65 vs 0.60 con p = 0.13) o al revés.',
 s:'PPT «2. Pruebas de Hipótesis», diap. 20 («Ambos métodos siempre llevan a la misma decisión») y lámina «Formas de tomar la decisión».'}

);
